### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by assasin541** [CobbleSword/NachoSpigot#10]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.                                                                                                                                                             1:compile (default-compile) on project api: Compilation failure: Compilation fai                                                                                                                                                             lure:
[ERROR] /root/nacho/NachoSpigot/NachoSpigot-API/src/main/java/org/spigotmc/Custo                                                                                                                                                             mTimingsHandler.java:[26] The import jdk.internal.reflect.Reflection cannot be r                                                                                                                                                             esolved
[ERROR] /root/nacho/NachoSpigot/NachoSpigot-API/src/main/java/org/spigotmc/Custo                                                                                                                                                             mTimingsHandler.java:[54] Reflection cannot be resolved

**Comment by DeadSteve51** [comment]
What plugins? What version?

**Comment by assasin541** [comment]
@DeadSteve51 what plugins? Newest version...

**Comment by Loyisa** [comment]
use java11

**Comment by CyberFlameGO** [comment]
^ @HeathLoganCampbell close :)

**Comment by Lucaskyy** [comment]
Fixed in current commit/release.

**Closing.**
