### ISSUE TITLE
"Loading terrain..."

### ISSUE THREAD

**Issue by AhmHkn0** [CobbleSword/NachoSpigot#111]
While connecting to server, if we use Flamecord as bungeecord fork, connection is fine, player can connect to the server.
If we use Aegis as bungeecord fork, connection has a problem it stays as connecting and the message is "Loading terrain...". Aegis has this problem only with Nacho, it has no problem any other spigot forks like Taco or Paper etc.

Can we please fix this problem?
https://puu.sh/HXy5r/88e5c3cef7.png

**Comment by Lucaskyy** [comment]
We can't do anything with this, sadly. Do any of the servers log anything about it?

**Comment by AhmHkn0** [comment]
There is not any error log or something, simply a join log as always. But player can't join the game and play because they stuck at "Loading terrain..." As i said it only happens with Nacho, other spigot forks do not have this issue.

https://puu.sh/HXyhv/e6913d79c5.png

**Comment by Lucaskyy** [comment]
Is this a clean install of NachoSpigot? If not, please try again using a clean install.

**Comment by AhmHkn0** [comment]
Yes it is clean install of NachoSpigot.

**Comment by Lucaskyy** [comment]
If I recall correctly though, Aegis is paid which means I can't reproduce your issue since I don't have Aegis. So sorry, I can't help you with this at this moment since I don't have the Aegis JAR or license.

**Comment by Rastrian** [comment]
I think the issue is related to the antibot void server feature, i will test with https://github.com/Leymooo/BungeeCord and see if i can reproduce the error.

**Comment by AhmHkn0** [comment]
I updated ProtocolLib and fixed this problem.
