### ISSUE TITLE
nettyBufferSize

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#113]
What does this setting do? What effects could you expect when increasing/lowering it?

**Comment by Lucaskyy** [comment]
It has been removed. See https://github.com/CobbleSword/NachoSpigot/pull/104#issuecomment-882735492

**Comment by andreasdc** [comment]
All right I guess I will wait with updating

**Comment by Lucaskyy** [comment]
Well.. you should update! nettyBufferSize might cause issues, and that's why I removed it.
