### ISSUE TITLE
Expect reduced performance

### ISSUE THREAD

**Issue by assasin541** [CobbleSword/NachoSpigot#12]
Why is it happening?

Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance
Less than 50% of values are sequential
1 out of 4
Expect reduced performance

**Comment by NathanPenwill** [comment]
Looks like this is a TacoSpigot thing (unless Nacho changed something)

This can be fixed by diabling `useArraysForBlockStates` in taco.yml

**Comment by assasin541** [comment]
@NathanPenwill so is it better to disable useArraysForBlockStates or let it be enabled?

**Comment by NathanPenwill** [comment]
Yes, disable it. After further investigation it actually looks like that is a removed TacoSpigot feature that Nacho kept

**Comment by CyberFlameGO** [comment]
@HeathLoganCampbell I think you’re good to go with closing this, you might wanna remove the `useArraysForBlockStates` taco.yml config option though

**Comment by Lucaskyy** [comment]
I will remove this.

Thank you!
