### ISSUE TITLE
Disabling world saving is not working

### ISSUE THREAD

**Issue by assasin541** [CobbleSword/NachoSpigot#13]
Even removing saving methods doesn't work.

**Comment by CyberFlameGO** [comment]
Not sure if this is still an issue, you can respond if it is/isn’t.

**Comment by Lucaskyy** [comment]
@assasin541 Please let us know if this is still an issue :)

**Comment by Lucaskyy** [comment]
No response, I will close this issue.

Please open a new issue if you still encounter this issue and if so, please tell us how to reproduce your issue so we can help you.
