### ISSUE TITLE
Possible improvement?

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#130]
Is it possible to apply these improvements to nacho?
https://github.com/astei/krypton

**Comment by andreasdc** [comment]
Another idea is that you can flush once in the end of every tick when sending packets.

**Comment by Ytnoos** [comment]
> Another idea is that you can flush once in the end of every tick when sending packets.

Wouldn't this delay packets and make a significant difference for pvp servers?

**Comment by andreasdc** [comment]
@Ytnoos we could do it for movement, chunk or similar packets, and/or call it with like 40 tps.

**Comment by Ytnoos** [comment]
> @Ytnoos we could do it for movement, chunk or similar packets, and/or call it with like 40 tps.

Movement packets are for sure the most sent but also the most important for PvP, we should see if this feature would bring a worth CPU usage decrease

**Comment by LewUwU** [comment]
> @Ytnoos we could do it for movement, chunk or similar packets, and/or call it with like 40 tps.

what if a desync is caused due to that change?

**Comment by LewUwU** [comment]
> Is it possible to apply these improvements to nacho?
> https://github.com/astei/krypton

not all due to license issues (velocity)

**Comment by andreasdc** [comment]
> > @Ytnoos we could do it for movement, chunk or similar packets, and/or call it with like 40 tps.
> 
> what if a desync is caused due to that change?

what desync?

**Comment by Ytnoos** [comment]
> > > @Ytnoos we could do it for movement, chunk or similar packets, and/or call it with like 40 tps.
> 
> > 
> 
> > what if a desync is caused due to that change?
> 
> 
> 
> what desync?

Many anticheats rely on fast packet response, transactions, arm animations and so on

**Comment by andreasdc** [comment]
@Ytnoos but its about sending packets, not receiving

**Comment by Ytnoos** [comment]
> @Ytnoos but its about sending packets, not receiving. You can choose which packets should be handled too.

In fact, why should the client wait up to 50ms to receive a packet which could be sent instantly, transaction and keepalives would be affected

**Comment by Lucaskyy** [comment]
^

**Comment by andreasdc** [comment]
Performance and smoothness improvement

**Comment by LewUwU** [comment]
> Performance and smoothness improvement

yeah, and 30 desync improvement

**Comment by andreasdc** [comment]
I don't think so

**Comment by MWHunter** [comment]
Here is how Tuinity implements this patch: https://github.com/Tuinity/Tuinity/blob/master/patches/server/0008-Allow-controlled-flushing-for-network-manager.patch


>  Many anticheats rely on fast packet response, transactions, arm animations and so on

I'm an anticheat dev.  This has no effect on anticheats.

**Comment by andreasdc** [comment]
> ic

It's already in nacho as i believe

**Comment by CyberFlameGO** [comment]
I meant the controlled flushing one

**Comment by Elierrr** [comment]
> Is it possible to apply these improvements to nacho? https://github.com/astei/krypton

This is (partially) done with #235.

**Comment by Lucaskyy** [comment]
> > > Here is how Tuinity implements this patch: https://github.com/Tuinity/Tuinity/blob/master/patches/server/0008-Allow-controlled-flushing-for-network-manager.patch
> > 
> > 
> > No, it's implemented in https://github.com/Tuinity/Tuinity/blob/master/patches/server/0066-Use-Velocity-compression-and-cipher-natives.patch
> 
> It would be nice to touch more packet sending, it's on top of my profilers, right after movement and ticking.

#236
