### ISSUE TITLE
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2ObjectOpenHashMap

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#131]
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2ObjectOpenHashMap
        at net.minecraft.server.v1_8_R3.NBTTagCompound.<init>(NBTTagCompound.java:16)
        at net.minecraft.server.v1_8_R3.ItemStack.C(ItemStack.java:747)
        at net.minecraft.server.v1_8_R3.StatisticList.c(SourceFile:137)
        at net.minecraft.server.v1_8_R3.StatisticList.a(SourceFile:90)
        at net.minecraft.server.v1_8_R3.DispenserRegistry.c(DispenserRegistry.java:658)
        at net.minecraft.server.v1_8_R3.MinecraftServer.main(MinecraftServer.java:1032)
        at org.bukkit.craftbukkit.Main.main(Main.java:236)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)

**Comment by Lucaskyy** [comment]
Fixed in #132

**Comment by Lucaskyy** [comment]
Actually, I misread that.

**Comment by Elierrr** [comment]
What causes this?

**Comment by LewUwU** [comment]
> java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2ObjectOpenHashMap
> at net.minecraft.server.v1_8_R3.NBTTagCompound.(NBTTagCompound.java:16)
> at net.minecraft.server.v1_8_R3.ItemStack.C(ItemStack.java:747)
> at net.minecraft.server.v1_8_R3.StatisticList.c(SourceFile:137)
> at net.minecraft.server.v1_8_R3.StatisticList.a(SourceFile:90)
> at net.minecraft.server.v1_8_R3.DispenserRegistry.c(DispenserRegistry.java:658)
> at net.minecraft.server.v1_8_R3.MinecraftServer.main(MinecraftServer.java:1032)
> at org.bukkit.craftbukkit.Main.main(Main.java:236)
> Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap
> at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
> at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
> at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)

Please, don't do invalid issues, how we can reproduce that? what version of nachospigot are you using? it's a modified one?

**Comment by andreasdc** [comment]
Changing fastutil from 8.4.4 to 8.5.4, it is modified.

**Comment by Lucaskyy** [comment]
> Changing fastutil from 8.4.4 to 8.5.4, it is modified.

Weirdly enough, it does compile. So what's going on here?

**Comment by andreasdc** [comment]
It shows wrong import

**Comment by andreasdc** [comment]
I use this jar https://mvnrepository.com/artifact/it.unimi.dsi/fastutil/8.5.4

**Comment by Lucaskyy** [comment]
For clarification, you use the latest NachoSpigot jar from https://nacho.sculas.xyz/ yeah?

**Comment by andreasdc** [comment]
> For clarification, you use the latest NachoSpigot jar from https://nacho.sculas.xyz/ yeah?

Not really, I apply changes manually

**Comment by Lucaskyy** [comment]
Then we won't provide support for that, sorry.

**Comment by andreasdc** [comment]
> Then we won't provide support for that, sorry.

fastutil-core is needed right?

**Comment by Lucaskyy** [comment]
> It shows wrong import

Also, if you know how to code you should know how to fix this :) If not, use your IDE.

**Comment by andreasdc** [comment]
> > It shows wrong import
> 
> Also, if you know how to code you should know how to fix this :) If not, use your IDE.

Yea, I fixed it. ❤️
