### ISSUE TITLE
Item fake disappear from player inventory when a block place is cancelled

### ISSUE THREAD

**Issue by imBuzz** [CobbleSword/NachoSpigot#133]
Hi, today i discovered a bug, i used paper 1.8 for month but, today i decided to use NachoSpigot and i've just found a bug, look the video.

**I'm sorry for the quality.**

https://youtu.be/ceoJVTSuoSY

Thanks
ImBuzz

**Comment by Lucaskyy** [comment]
That's not supposed to happen.

Could you try to reproduce this with TacoSpigot 1.8.8? Would like to see if this is a NachoSpigot issue.

**Comment by imBuzz** [comment]
Hi, i can't compile a TacoSpigot, i don't know the reason but i doesn't find Paperclip. Have you tried this "bug"?

**Comment by imBuzz** [comment]
Because with Paper 1.8.8 it doesn't appear

**Comment by Lucaskyy** [comment]
> Hi, i can't compile a TacoSpigot, i don't know the reason but i doesn't find Paperclip. Have you tried this "bug"?

Stop using others issues for this, go make your own. Also, this is NachoSpigot, not TacoSpigot. Go to their GitHub repository and ask them. We do not provide support for issues like this.

**Comment by Lucaskyy** [comment]
Here's the download for TacoSpigot 1.8: https://anonfiles.com/f0G5h29eu2/server-1.8_jar

This is a JAR file, so you don't need to compile it yourself.

**Comment by imBuzz** [comment]
This site it's off right now, i'm waiting until it will be online. Thanks ;)

**Comment by Lucaskyy** [comment]
The link I've sent you works fine for me?

**Comment by imBuzz** [comment]
Ah, can you upload it on Mediafire or Dropbox ? I can't see the site look this: [https://gyazo.com/92cb411a0c8d494d7e2859048468946f](url)

**Comment by Lucaskyy** [comment]
Check your DMs on Discord :)

**Comment by imBuzz** [comment]
Hi, that bug does not appear with TacoSpigot 1.8.8

**Comment by Marcelektro** [comment]
Do you have “spawn protection” set to 0 in server.properties?
If yes, do you get any errors on the console? I also faced this issue, not sure how did I fix it tho. 
You may also try enabling itemstack reading on place in nacho.json
