### ISSUE TITLE
Trim chat components issue

### ISSUE THREAD

**Issue by poyrazinan** [CobbleSword/NachoSpigot#135]
Hello,

Nacho trim chat components

Explanation in video: (First Paper, Second Nacho)
https://youtu.be/xnmmoiL-j_Y

**Comment by Rastrian** [comment]
I can take a look into this after update the current knockback system, which errors do you get when the plugin try trim? any response or console output about that? This plugin its public for test issues?

**Comment by CyberFlameGO** [comment]
Hmm, I'm not sure but it looks like a CMI issue?

**Comment by TheGeyik** [comment]
It's probaby chat component issue.

> Hmm, I'm not sure but it looks like a CMI issue?

It can be about CMI becuase i've checked tacho & spigot & paper etc. and this issue only occure on nacho latest.
It works old version of nacho but i've updated it and this issue occured afterwards.
(I'm not sure about old version but i've installed before ghost spawner issue fix)

**Comment by tomasalves8** [comment]
Stale Issue. We should probably close this.  @Lucaskyy
