### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#138]
Can you add reloading nacho settings from command? :)

**Comment by Rastrian** [comment]
I will add new nacho commands soon.

**Comment by CyberFlameGO** [comment]
I personally don't think it's a good idea but if that's what people want 🤷‍♂️

**Comment by Marcelektro** [comment]
Most settings wouldn’t be useful anyway, as the options are used just at the startup.

**Comment by andreasdc** [comment]
> Most settings wouldn’t be useful anyway, as the options are used just at the startup.

It would be easier to test experimental options and if people will find any problems with settings, they could change that without restarting. :)

**Comment by Rastrian** [comment]
i think the idea its allow some settings be changed only, like MobAI, PlayerMoveEvent, etc.
