### ISSUE TITLE
Weird block updates?

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#144]
When I send block change packet for grass block and walk to another block, block at the location is updated to the original one, when I move further, block is sent by me. I hope you understand. :P
I noticed it only with grass blocks.

**Comment by LewUwU** [comment]
Please, send a video showing the bug or better, the code that you use so we can see a possible fix or if is something wrong in your code.

**Comment by andreasdc** [comment]
@LewUwU unbelievable, it's happening because of block connection from ViaVersion...

**Comment by LewUwU** [comment]
Then, is not a bug from NachoSpigot, can you close this?

**Comment by andreasdc** [comment]
> ?

true, but can you improve vv's code from block connection?

**Comment by CyberFlameGO** [comment]
Does it occur on regular Paper?

**Comment by Lucaskyy** [comment]
Our VV "patch" doesn't patch anything, it just enables the patch.

**Comment by andreasdc** [comment]
> Does it occur on regular Paper?

Probably yes, it comes from VV blockconnection.

> Our VV "patch" doesn't patch anything, it just enables the patch.

That's some idea for improvement, or maybe backporting serverside block connections

**Comment by crafter23456** [comment]
Or ask ViaRewind to fix it because thats their goal

**Comment by andreasdc** [comment]
> Or ask ViaRewind to fix it because thats their goal

That's from ViaVersion

**Comment by CyberFlameGO** [comment]
This issue is stale and I feel like its remedy is currently out of Nacho's scope

**Comment by andreasdc** [comment]
ViaVersion's cause
