### ISSUE TITLE
Is this good enough for production?

### ISSUE THREAD

**Issue by FurmigaHumana** [CobbleSword/NachoSpigot#145]
I currently use a custom 1.8 paper build, I added java 16 support and a bunch of things you guys already did here so is not worth it for me to maintain a private build all by myself, my server is OK-sized and I am willing to give this a try and may even provide some PR and performance profiles, but I am wondering if this is in an early stage of development or has been already tested in an actual production environment?

**Comment by Lucaskyy** [comment]
Nacho is mostly production ready (as always, there might be bugs) and it has been tested in 100~ players servers, but we need people to test with more :)
