### ISSUE TITLE
Setting biomes doesn't work

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#147]
Setting biomes doesn't work

**Comment by AhmHkn0** [comment]
Setting biomes works on my NachoSpigot server. Are you sure doing everything right?

**Comment by andreasdc** [comment]
What code do you use for setting biomes? For me in best scenario 1 chunk is changing

**Comment by AhmHkn0** [comment]
`//setbiome <biome>`

**Comment by CyberFlameGO** [comment]
Are you relogging after you do it? Iirc it's cached in your client

**Comment by AhmHkn0** [comment]
Of course. You have to reload chunk you changed.

**Comment by andreasdc** [comment]
Yes, I change it (worldedit or bukkit api), do /save-all, restart the server and relog. In the best scenario maybe 1 chunk will change.

**Comment by AhmHkn0** [comment]
I changed biome here (More than 1 chunk) then I restarted server and everything is okay.
https://puu.sh/I3YSw/5eecd1e2df.png

**Comment by andreasdc** [comment]
Keep spawn enabled and doing it near spawn? You set positions and then //setbiome? Multiverse? Custom chunk generator?

**Comment by AhmHkn0** [comment]
No. Yes. Yes but I changed biome at default world (world). No.

**Comment by andreasdc** [comment]
For me only couple blocks changes

**Comment by AhmHkn0** [comment]
So problem is not NachoSpigot.

**Comment by andreasdc** [comment]
So what problem when its on nacho?

**Comment by CyberFlameGO** [comment]
Can you try replicating this attempt on TacoSpigot's last successful 1.8.8 artifact and PaperSpigot build 443? I'd like to see if the functionality you're reporting is present upstream

**Comment by andreasdc** [comment]
Send me links I can try to give a look

**Comment by CyberFlameGO** [comment]
Try
https://papermc.io/api/v2/projects/paper/versions/1.8.8/builds/443/downloads/paper-1.8.8-443.jar
and let me know, and if it works as intended I'll send you a TacoSpigot
download

**Comment by CyberFlameGO** [comment]
@andreasdc did you try this?

**Comment by andreasdc** [comment]
[00:14:05] [Server thread/WARN]: java.lang.NoSuchFieldException: modifiers

[00:14:05] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)

[00:14:05] [Server thread/WARN]: 	at org.github.paperspigot.PaperSpigotConfig.stackableBuckets(PaperSpigotConfig.java:192)

[00:14:05] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[00:14:05] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)

[00:14:05] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[00:14:05] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)

[00:14:05] [Server thread/WARN]: 	at org.github.paperspigot.PaperSpigotConfig.readConfig(PaperSpigotConfig.java:84)

[00:14:05] [Server thread/WARN]: 	at org.github.paperspigot.PaperSpigotConfig.init(PaperSpigotConfig.java:62)

[00:14:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:181)

[00:14:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)

[00:14:05] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Lucaskyy** [comment]
@andreasdc Does this still happen on base NachoSpigot?

**Comment by andreasdc** [comment]
> @andreasdc Does this still happen on base NachoSpigot?

Yes it is.

**Comment by Lucaskyy** [comment]
Okay. Could you try to reproduce this on Paper (link above) and Java 8 (which fixed the error you have)?

**Comment by andreasdc** [comment]
> Okay. Could you try to reproduce this on Paper (link above) and Java 8 (which fixed the error you have)?

I don't have Java 8. Just try setting biomes with worldedit or custom plugin and it won't change all blocks/chunks.

**Comment by Lucaskyy** [comment]
I'll try it myself then, but you know you can just install Java 8 right? Not that hard :P

**Comment by andreasdc** [comment]
> I'll try it myself then, but you know you can just install Java 8 right? Not that hard :P

Probably harder than running paper with worldedit on it :P

**Comment by Lucaskyy** [comment]
Eh, it's literally just going to Oracle's download page and click on the right one. Then just install it. On the other hand, I have to find Paper and WorldEdit and then get a new server up and running to test it ;)

**Comment by andreasdc** [comment]
> Eh, it's literally just going to Oracle's download page and click on the right one. Then just install it. On the other hand, I have to find Paper and WorldEdit and then get a new server up and running to try and reproduce it ;)

It's literally downloading paper from link above and finding worldedit for 1.8 and running it. :) /And then //setbiome

**Comment by Lucaskyy** [comment]
Just tested it on the latest build of NachoSpigot with FastAsyncWorldEdit on Java 8 and I cannot reproduce your issue.
It does perfectly what it should, also with multiple chunks.

**Comment by andreasdc** [comment]
> Just tested it on the latest build of NachoSpigot with FastAsyncWorldEdit on Java 8 and I cannot reproduce your issue. It does perfectly what it should, also with multiple chunks.

Can you send screenshto and use worldedit not fawe?

**Comment by Lucaskyy** [comment]
FAWE is WorldEdit though? It uses WorldEdit behind the scenes. So there's no change in that.
And screenshots? If you just want to see some plains grass and some swampland grass next to that, then sure 🤷‍♂️

**Comment by andreasdc** [comment]
> FAWE is WorldEdit though? It uses WorldEdit behind the scenes. So there's no change in that. And screenshots? If you just want to see some plains grass and some swampland grass next to that, then sure 🤷‍♂️

I don't know, I use worldedit and with custom plugin it was the same.
I picked region, only some chunks were changed, that's why I want to see before and after.

**Comment by Lucaskyy** [comment]
![Img](https://us-east-1.tixte.net/uploads/brayden.sucks-ass.lol/javaw_Uh9VgGNRRJ.png)

**Comment by Lucaskyy** [comment]
> I don't know, I use worldedit and with custom plugin it was the same. I picked region, only some chunks were changed, that's why I want to see before and after.

Have you tried without the custom plugin? And ***only*** WorldEdit on your server? Also, on NachoSpigot, not anything else :P

**Comment by andreasdc** [comment]
> > I don't know, I use worldedit and with custom plugin it was the same. I picked region, only some chunks were changed, that's why I want to see before and after.
> 
> Have you tried without the custom plugin? And _**only**_ WorldEdit on your server? Also, on NachoSpigot, not anything else :P

Yea I just did that couple messages above. I see only 1 chunk changed, try setting like 20 at once, how are you going to check if all chunks changed if you pick 1 chunk?

**Comment by Lucaskyy** [comment]
Then I'd have to do that later, currently using TeamViewer and it's almost impossible to move in Minecraft :P

**Comment by andreasdc** [comment]
> Then I'd have to do that later, currently using TeamViewer and it's almost impossible to move in Minecraft :P

There is something like PojavLauncher

**Comment by UnnamedWarrior** [comment]
> > Then I'd have to do that later, currently using TeamViewer and it's almost impossible to move in Minecraft :P
> 
> There is something like PojavLauncher

I use pojavlauncher when im on my phone , and setting biome does work for me on latest nacho but i use FAWE

**Comment by Lucaskyy** [comment]
Plugins:
```
>pl
[16:40:03 INFO]: Plugins (5): WorldEdit, spark, ViaVersion, ProtocolLib, packetevents
```
WorldEdit Version:
```
>worldedit version
[16:40:25 INFO]: WorldEdit version (unknown)
[16:40:25 INFO]: https://github.com/sk89q/worldedit/
[16:40:25 INFO]: ----------- Platforms -----------
[16:40:25 INFO]: * Bukkit-Official (6.1.9;caf0ad9)
[16:40:25 INFO]: ----------- Capabilities -----------
[16:40:25 INFO]: GAME_HOOKS: Bukkit-Official
[16:40:25 INFO]: CONFIGURATION: Bukkit-Official
[16:40:25 INFO]: USER_COMMANDS: Bukkit-Official
[16:40:25 INFO]: PERMISSIONS: Bukkit-Official
[16:40:25 INFO]: WORLDEDIT_CUI: Bukkit-Official
[16:40:25 INFO]: WORLD_EDITING: Bukkit-Official
```
![Img](https://us-east-1.tixte.net/uploads/brayden.sucks-ass.lol/javaw_iGzyD6C1du.jpg)
I cannot reproduce your issue, it works as expected for me.
@andreasdc

**Comment by andreasdc** [comment]
> Plugins:
> 
> ```
> >pl
> [16:40:03 INFO]: Plugins (5): WorldEdit, spark, ViaVersion, ProtocolLib, packetevents
> ```
> 
> WorldEdit Version:
> 
> ```
> >worldedit version
> [16:40:25 INFO]: WorldEdit version (unknown)
> [16:40:25 INFO]: https://github.com/sk89q/worldedit/
> [16:40:25 INFO]: ----------- Platforms -----------
> [16:40:25 INFO]: * Bukkit-Official (6.1.9;caf0ad9)
> [16:40:25 INFO]: ----------- Capabilities -----------
> [16:40:25 INFO]: GAME_HOOKS: Bukkit-Official
> [16:40:25 INFO]: CONFIGURATION: Bukkit-Official
> [16:40:25 INFO]: USER_COMMANDS: Bukkit-Official
> [16:40:25 INFO]: PERMISSIONS: Bukkit-Official
> [16:40:25 INFO]: WORLDEDIT_CUI: Bukkit-Official
> [16:40:25 INFO]: WORLD_EDITING: Bukkit-Official
> ```
> 
> ![Img](https://camo.githubusercontent.com/df4c8db1e0e7213d0f0646570226d8b899b6d7a5235c69c1d4819ea184ca3c21/68747470733a2f2f75732d656173742d312e74697874652e6e65742f75706c6f6164732f6272617964656e2e7375636b732d6173732e6c6f6c2f6a617661775f69477a794436433164752e6a7067) I cannot reproduce your issue, it works as expected for me. @andreasdc

Do it on NachoSpigot now

**Comment by Lucaskyy** [comment]
This.. was on NachoSpigot?

**Comment by Lucaskyy** [comment]
@andreasdc

**Comment by andreasdc** [comment]
> This.. was on NachoSpigot?

Yea error was on NachoSpigot

**Comment by Lucaskyy** [comment]
Well, I had no issues, and I cannot reproduce your issue. It works perfectly fine for me, on NachoSpigot. I have the exact same environment as yours, as you told me, so this issue is definitely on your end. Unless you can prove that this is NachoSpigot's fault, I will close this issue. Try to reproduce your issue on the latest version of NachoSpigot by downloading it from here, not your fork please, and only install WorldEdit. Nothing else. If you can still reproduce it, and you're not in spawn (due to spawn protection, I'm not sure if WorldEdit bypasses this) or whatever then please reopen this issue.

**Comment by andreasdc** [comment]
> Well, I had no issues, and I cannot reproduce your issue. It works perfectly fine for me, on NachoSpigot. I have the exact same environment as yours, as you told me, so this issue is definitely on your end. Unless you can prove that this is NachoSpigot's fault, I will close this issue. Try to reproduce your issue on the latest version of NachoSpigot by downloading it from here, not your fork please, and only install WorldEdit. Nothing else. If you can still reproduce it, and you're not in spawn (due to spawn protection, I'm not sure if WorldEdit bypasses this) or whatever then please reopen this issue.

I just reproduced it on NachoSpigot, you tried on Paper and you say it works on Nacho?

**Comment by andreasdc** [comment]
What do you mean by not in spawn?

**Comment by Lucaskyy** [comment]
> you tried on Paper and you say it works on Nacho?
Ah, misunderstanding. No, I tried it on NachoSpigot first to see if I can even reproduce it or not.
> What do you mean by not in spawn?
Well, spawn protection might interfere with WorldEdit. Not sure though.
> I just reproduced it on NachoSpigot
So, you just downloaded the latest build, and tried it with only WorldEdit on your server? Nothing else, like I said?

**Comment by andreasdc** [comment]
> > you tried on Paper and you say it works on Nacho?
> 
> Ah, misunderstanding. No, I tried it on NachoSpigot first to see if I can even reproduce it or not.
> 
> > What do you mean by not in spawn?
> 
> Well, spawn protection might interfere with WorldEdit. Not sure though.
> 
> > I just reproduced it on NachoSpigot
> 
> So, you just downloaded the latest build, and tried it with only WorldEdit on your server? Nothing else, like I said?

Exactly, but I did that close to spawn

**Comment by Lucaskyy** [comment]
Could you try to reproduce it far away from spawn?

**Comment by andreasdc** [comment]
stop-notify-bungee: false is freezing my server btw

**Comment by Lucaskyy** [comment]
It only freezes your server for 10 seconds, so you can read the message. But it's good that it freezes your server because it means you have a security vulnerability :)

**Comment by andreasdc** [comment]
> It only freezes your server for 10 seconds, so you can read the message. But it's good that it freezes your server because it means you have a security vulnerability :)

There is no message, I don't have any vulnerabilities

**Comment by andreasdc** [comment]
external != the one that I'm using

**Comment by Lucaskyy** [comment]
> external != the one that I'm using

Uhh, that makes no sense to me. If your Minecraft server is accessible from the outside world and you have BungeeCord support enabled, that is a security risk/vulnerability.

I hope you know what BungeeHack/BungeeSpoof is, lol.

**Comment by andreasdc** [comment]
> > external != the one that I'm using
> 
> Uhh, that makes no sense to me. If your Minecraft server is accessible from the outside world and you have BungeeCord support enabled, that is a security risk/vulnerability.
> 
> I hope you know what BungeeHack/BungeeSpoof is, lol.

It's not running on external ip and nobody has address of this machine too.

**Comment by andreasdc** [comment]
I tried changing serverside-blockconnections to false, but still only some chunks changed.

**Comment by Lucaskyy** [comment]
> It's not running on external ip and nobody has address of this machine too.

Getting the address is easy if you're not using a proxy such as Cloudflare Spectrum.
Also, your server is externally accessible. The checker grabs the external IP address, and then tries to connect to your external IP and MC server port, which is succeeds in which means other people can access your server.

> I tried changing serverside-blockconnections to false, but still only some chunks changed.

Please refer to my comment:
https://github.com/CobbleSword/NachoSpigot/issues/147#issuecomment-973071821
> I cannot reproduce your issue as I said before. You can make a video if you want, showing you reproducing it. Also make sure to only install WorldEdit and be on the latest version of NachoSpigot (I'm repeating myself, just to be sure).

**Comment by Lucaskyy** [comment]
Actually, your server shouldn't freeze with `stop-notify-bungee` on false.
It might freeze for a short time since it has to send an HTTP request and then open a socket.
But it shouldn't freeze for a long time.

**Comment by andreasdc** [comment]
> Actually, your server shouldn't freeze with `stop-notify-bungee` on false. It might freeze for a short time since it has to send an HTTP request and then open a socket. But it shouldn't freeze for a long time.

Around 30 seconds. You check if I have access to world, not if world has access to me, right?

**Comment by andreasdc** [comment]
I'm using WorldEdit, WorldGuard and ViaVersion. I can try with other WE version later. Do you want me to have something set up specifically?

**Comment by Lucaskyy** [comment]
I was using WorldEdit 6.1.9. Remove WorldGuard for the time, since I told you only to use WorldEdit (ViaVersion isn't a problem).

**Comment by andreasdc** [comment]
> I was using WorldEdit 6.1.9. Remove WorldGuard for the time, since I told you only to use WorldEdit (ViaVersion isn't a problem).

With what Java?

**Comment by Lucaskyy** [comment]
Java 8, but that shouldn't make a difference on what the outcome is.
I just used Java 8 since FAWE doesn't work on newer versions of Java.

**Comment by andreasdc** [comment]
> Java 8, but that shouldn't make a difference on what the outcome is. I just used Java 8 since FAWE doesn't work on newer versions of Java.

We have to use exact same environment and exact server settings to check this, I will generate fresh folder and use different WorldEdit.
