### ISSUE TITLE
Taco patch

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#148]
https://github.com/TacoSpigot/TacoSpigot/blob/master/Paper-Server-Patches/0008-Use-arrays-for-blockstates.patch
This patch is master TacoSpigot, maybe it could be added? I think it was removed.

**Comment by andreasdc** [comment]
And this one I don't know if it's the same 
https://github.com/TacoSpigot/TacoSpigot/blob/master/fire-pit/0012-Use-arrays-to-manage-blockstates-saving-memory-and-i.patch

**Comment by CyberFlameGO** [comment]
I'm willing to work on this. The first patch isn't present in Taco's 1.8.8 branch AFAIK and I'm too tired to figure out if it's actually compatible. [Here's](https://github.com/TacoSpigot/TacoSpigot/tree/version/1.8.8/) the branch for reference though. Keep me posted \(I'd do it myself but I'm not gonna remember when I wake up and it's 2:40AM ATM haha\)

**Comment by Elierrr** [comment]
> And this one I don't know if it's the same
> https://github.com/TacoSpigot/TacoSpigot/blob/master/fire-pit/0012-Use-arrays-to-manage-blockstates-saving-memory-and-i.patch

We probably shouldn't do this one, looks like it caused issues with TacoSpigot and probably wouldn't be compatible with the other patch.

**Comment by andreasdc** [comment]
I have to point that I think that we had this thing in Nacho, but enabling it caused spam in the console about lowerred performance, but they have this thing in Taco's master, so I don't know.

**Comment by LewUwU** [comment]
> I have to point that I think that we had this thing in Nacho, but enabling it caused spam in the console about lowerred performance, but they have this thing in Taco's master, so I don't know.

Taco is abandoned

**Comment by andreasdc** [comment]
> > I have to point that I think that we had this thing in Nacho, but enabling it caused spam in the console about lowerred performance, but they have this thing in Taco's master, so I don't know.
> 
> Taco is abandoned

Yea but they kept this patch for couple years

**Comment by CyberFlameGO** [comment]
> > I have to point that I think that we had this thing in Nacho, but enabling it caused spam in the console about lowerred performance, but they have this thing in Taco's master, so I don't know.
> 
> Taco is abandoned

In my opinion its project status is irrelevant to this issue.

**Comment by CyberFlameGO** [comment]
I'm confused, this (NachoSpigot) is a fork of TacoSpigot yet our [net.minecraft.server.Block](https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/net/minecraft/server/Block.java) isn't the same as the content in [this patch](https://github.com/TacoSpigot/TacoSpigot/blob/version/1.8.8/fire-pit/0012-Use-arrays-to-manage-blockstates-saving-memory-and-i.patch). [net.techable.tacospigot.BlockStateRegistry](https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/net/techcable/tacospigot/BlockStateRegistry.java) exists though. @HeathLoganCampbell thoughts?

**Comment by Elierrr** [comment]
> I'm confused, this (NachoSpigot) is a fork of TacoSpigot yet our [net.minecraft.server.Block](https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/net/minecraft/server/Block.java) isn't the same as the content in [this patch](https://github.com/TacoSpigot/TacoSpigot/blob/version/1.8.8/fire-pit/0012-Use-arrays-to-manage-blockstates-saving-memory-and-i.patch). [net.techable.tacospigot.BlockStateRegistry](https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/net/techcable/tacospigot/BlockStateRegistry.java) exists though. @HeathLoganCampbell thoughts?

It's not in the patches, it's in the fire-pit. Probably because it caused a bug.

**Comment by andreasdc** [comment]
> > I'm confused, this (NachoSpigot) is a fork of TacoSpigot yet our [net.minecraft.server.Block](https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/net/minecraft/server/Block.java) isn't the same as the content in [this patch](https://github.com/TacoSpigot/TacoSpigot/blob/version/1.8.8/fire-pit/0012-Use-arrays-to-manage-blockstates-saving-memory-and-i.patch). [net.techable.tacospigot.BlockStateRegistry](https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/net/techcable/tacospigot/BlockStateRegistry.java) exists though. @HeathLoganCampbell thoughts?
> 
> It's not in the patches, it's in the fire-pit. Probably because it caused a bug.

They have 2 patches, 1 in master and 1 in fire-pit.

**Comment by Elierrr** [comment]
>[net.techable.tacospigot.BlockStateRegistry](https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/net/techcable/tacospigot/BlockStateRegistry.java) exists though.

Also, that's not the same file as the one in the patch. It's BlockDataRegistry.

**Comment by CyberFlameGO** [comment]
Ah my bad haha

**Comment by andreasdc** [comment]
https://github.com/CobbleSword/NachoSpigot/issues/12

**Comment by Lucaskyy** [comment]
This issue is stale, closing.
