### ISSUE TITLE
Spawners too fast

### ISSUE THREAD

**Issue by AhmHkn0** [CobbleSword/NachoSpigot#149]
Why spawners too fast?

https://www.youtube.com/watch?v=PgoOg265wG4

**Comment by Elierrr** [comment]
Are you using a plugin? Doesn't seem like something that would be caused by NachoSpigot

**Comment by AhmHkn0** [comment]
This problem has been happening since I installed NachoSpigot. It didn't happen before. It happens some time after the server is up.

**Comment by Rastrian** [comment]
Can you give me your configs for reproduce the error? (nacho.json, paper, server.proprieties, spigot.yml and others)

**Comment by AhmHkn0** [comment]
Spawner options is default in that files. I didn't change any option about spawner options.

**Comment by Elierrr** [comment]
I'm unable to reproduce this. This seems to be a problem an issue with a plugin running on NachoSpigot.  

I see that you are using 1.12.2, can you reproduce this on 1.8?
