### ISSUE TITLE
Ops don't load from the file.

### ISSUE THREAD

**Issue by sadcenter** [CobbleSword/NachoSpigot#150]
^^ Every server restart, ops disappear.

**Comment by 0ptk** [comment]
you are using maybe fast ops in cfg ?

**Comment by sadcenter** [comment]
I'm.

**Comment by Memexurer** [comment]
jebac cie sadcenter

**Comment by Memexurer** [comment]
:trollface:

**Comment by Elierrr** [comment]
Please reopen this issue as it is still a bug.

**Comment by windcolor-dev** [comment]
I don't think this is a bug, I think that the fast op setting is supposed to deop you when you restart the server.

**Comment by Elierrr** [comment]
> I don't think this is a bug, I think that the fast op setting is supposed to deop you when you restart the server.

There is no reason to have a setting that deops you after a server restart.

The fast ops setting loads operators faster, however it seems that the implementation is incorrect.

**Comment by windcolor-dev** [comment]
Ah that may be correct.

**Comment by Elierrr** [comment]
After testing, it seems that the config loads after the operators so the server thinks that there is no operators on startup

**Comment by Rastrian** [comment]
Why just don't disable option in config ?
