### ISSUE TITLE
Chunks never unload

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#151]
The entries in Long2ObjectOpenHashMap used in ChunkProviderServer seems to never be removed causing a memory leak.
I ran a server for 24h with few players, but still the map ended up holding 5600+ chunks with 1 player online. 
![pC4Bo5z](https://user-images.githubusercontent.com/50603525/131031767-d3b3dd83-b88d-431e-ba36-e96ca48310f5.png)

I can't find any reason for the server to hold 5k+ chunks in memory.

Configuration attached
[spigot.yml.txt](https://github.com/CobbleSword/NachoSpigot/files/7062604/spigot.yml.txt)
[taco.yml.txt](https://github.com/CobbleSword/NachoSpigot/files/7062605/taco.yml.txt)
[bukkit.yml.txt](https://github.com/CobbleSword/NachoSpigot/files/7062606/bukkit.yml.txt)
[nacho.json.txt](https://github.com/CobbleSword/NachoSpigot/files/7062609/nacho.json.txt)
[paper.yml.txt](https://github.com/CobbleSword/NachoSpigot/files/7062612/paper.yml.txt)

**Comment by Sneakometer** [comment]
Can really verify because "vanilla" paper only runs on java 8 and most of our plugins require java 11. 
I will do some localhost testing later.

**Comment by LewUwU** [comment]
What are you using to see the content of the chunk map? i can try testing on default paper if i have the tool

**Comment by Sneakometer** [comment]
Eclipse Memory Analyzer, you can find it here: https://www.eclipse.org/mat/downloads.php
Create a heap dump using `jmap -dump:live,format=b,file=dump-dump.hprof <JVM-PID>` and load it in the program. Quite useful for inspecting memory leaks.

**Comment by Elierrr** [comment]
Can you test without your plugins? I'm unable to reproduce this.

**Comment by andreasdc** [comment]
Don't you have option doChunkUnload?

**Comment by Sneakometer** [comment]
Actually, i think setting autosave to -1 caused this on our lobby servers. I'm not sure if it is a desired behavior to never unload any chunks if autosave is disabled.

**Comment by tomasalves8** [comment]
https://github.com/CobbleSword/NachoSpigot/blob/00a3d3bb568d26b7938cf6e00cc82f473fe196e8/NachoSpigot-Server/src/main/java/net/minecraft/server/ChunkProviderServer.java#L405-L406

Turns out both the saving and unloading operations are only done when saving is enabled, I don't believe this is intended. I'll make a PR for this soon.

**Comment by Sneakometer** [comment]
Thanks!

**Comment by Lucaskyy** [comment]
Oh wow, that I never noticed that. Thanks @tomasalves8 for finding it!
