### ISSUE TITLE
Implement Starlight

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#155]
Can you implement Startlight as Paper did? Paper merged all Tuinity patches too, maybe there are more that can be added to Nacho?

**Comment by Lucaskyy** [comment]
Don't forget Starlight is 1.16/1.17, and so is Paper. So backporting an entire lighting engine is too much work for a free project like this (at least, for me). Though, if someone's willing to take up the task for themselves you are totally welcome to do so.

**Comment by andreasdc** [comment]
> Don't forget Starlight is 1.16/1.17, and so is Paper. So backporting an entire lighting engine is too much work for a free project like this (at least, for me). Though, if someone's willing to take up the task for themselves you are totally welcome to do so.

That would be cool change
