### ISSUE TITLE
READ THIS ISSUE !! The Future of NachoSpigot

### ISSUE THREAD

**Issue by Lucaskyy** [CobbleSword/NachoSpigot#17]
Hi there,

Because NachoSpigot is abandoned, I am continuing the project myself at https://github.com/Sculas/NachoSpigot

I have added Java 8 support, Java 15 is now also supported (Java 8 to 15)

I have added a lot of patches to make Nacho stable. ProtocolLib bug has been fixed by modifying the ProtocolInjector class from ProtocolLib at runtime. This is stable.

ViaVersion's block placement fix has now also been applied when some checks done by ViaVersion are falsy.

Please post issues/bugs here or in the Discord.
PRs should be done at my repo.

Please note that my fork is community-ran and that in no way Heath/Sprock has ever said that I am allowed to take over the project. I am purely doing this to keep something alive that had a potential to be something good.

Have a good one!

**Comment by CyberFlameGO** [comment]
We’ve merged your changes to the upstream repo :)
Cheers

**Comment by Lucaskyy** [comment]
Thank you! :)
