### ISSUE TITLE
[Suggestion] Optimize entity move and player ticking

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#181]
EnityPlayer, EntityHuman and EntityLiving is pretty slow, it shows really bad on profilers, could it be optimized? Entity.move() method is pretty slow too, I see similar optimization in Tuinity.

**Comment by CyberFlameGO** [comment]
If possible could you please send a comparison profiling?

**Comment by Rastrian** [comment]
I didn't touch into entity movement yet, but feel free to test: https://github.com/CobbleSword/NachoSpigot/pull/231

**Comment by andreasdc** [comment]
> I didn't touch into entity movement yet, but feel free to test: #231

Movement I already optimized by some, I would take a big look into ticking (bottom screenshot) and packet sending.
Some of your changes are cool, I'm heading to test TE ticking. :)

**Comment by Lucaskyy** [comment]
Closing this for now. Might want to look into this later on.
