### ISSUE TITLE
[Suggestion] Optimize packet sending

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#185]
Sending packets is on top of profilers, is there a way to optimize it?

**Comment by Rastrian** [comment]
> Sending packets is on top of profilers, is there a way to optimize it?

Could woul send me the spark link about this usage?

**Comment by andreasdc** [comment]
> > Sending packets is on top of profilers, is there a way to optimize it?
> 
> Could you send me the spark link about this usage?

![image](https://user-images.githubusercontent.com/82218780/141605962-a6be266c-0f89-4b4c-a8cd-c5f2bcb2822b.png)

It is something like that, I tried adding fastutil to EnumProtocol.a(), but I don't know how to compare performance.

**Comment by Rastrian** [comment]
> > > Sending packets is on top of profilers, is there a way to optimize it?
> > 
> > 
> > Could you send me the spark link about this usage?
> 
> ![image](https://user-images.githubusercontent.com/82218780/141605962-a6be266c-0f89-4b4c-a8cd-c5f2bcb2822b.png)
> 
> It is something like that, I tried adding fastutil to EnumProtocol.a(), but I don't know how to compare performance.
> 
> Let me know if you need anything more.

dispatchPacket optimization is really a pain in the ass, i will take a look soon.

**Comment by andreasdc** [comment]
> > > > Sending packets is on top of profilers, is there a way to optimize it?
> > > 
> > > 
> > > Could you send me the spark link about this usage?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/82218780/141605962-a6be266c-0f89-4b4c-a8cd-c5f2bcb2822b.png)
> > It is something like that, I tried adding fastutil to EnumProtocol.a(), but I don't know how to compare performance.
> > Let me know if you need anything more.
> 
> dispatchPacket optimization is really a pain in the ass, i will take a look soon.

I would love to see optimization on this, I can show you other hot methods here or on discord, btw getPlayer method is only used for logging as I see? xD

**Comment by sadcenter** [comment]
#232

**Comment by Lucaskyy** [comment]
https://github.com/CobbleSword/NachoSpigot/pull/236#issuecomment-968307643
cc: @andreasdc

**Comment by andreasdc** [comment]
> c

yes?
