### ISSUE TITLE
Building with macro/fast clicking on 1.9+

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#19]
When you fast build on 1.9+, for example 1.16.5, your placing often gets cancelled. It's especially frustrating when you build bridges. It happens, because when you use ViaVersion, your blocks get placed inside you. Even when you bypass that and block placing inside yourself (no ViaVersion patch, fixed block placement inside the spigot) your placing gets blocked.

**Comment by Lucaskyy** [comment]
Does this have anything to do with NachoSpigot? This seems more like a ViaVersion issue to me.

**Comment by Lucaskyy** [comment]
After some talking, we found out this is a ViaVersion issue and not a NachoSpigot issue.

I will look at this either way sometime, but I am closing this because this has nothing to do with NachoSpigot.
