### ISSUE TITLE
add disable fall animation

### ISSUE THREAD

**Issue by BakuQ** [CobbleSword/NachoSpigot#203]
Added ability to disable falling sand, gravel, anvil etc. It means the server will not lag when a large number of items drops and it will improve client-side fps

**Comment by sadcenter** [comment]
@CyberFlameGO yea, there is an option to disable entire blocks physics, but not the falling animation. I think the author means to add an option to disable falling blocks animation

https://user-images.githubusercontent.com/55924469/138169040-2b2c00e9-71ff-4b57-9cbf-1fba6d81eb05.mp4

**Comment by sadcenter** [comment]
I think there IS a point. if you combine TNT with a lot of sand -  it can lag the entire server. Some polish servers had a problem with that for a moment. https://youtu.be/u9agMUXHY1Q?t=541

**Comment by BakuQ** [comment]
> @CyberFlameGO yea, there is an option to disable entire blocks physics, but not the falling animation. I think the author means to add an option to disable falling blocks animation
> 
>  2021-10-20.22-44-08.mp4

that's what I mean. This would improve server performance

**Comment by BakuQ** [comment]
> Can someone test the difference between disablePhysicsPlace and disablePhysicsUpdate and let me know? Also, do either of those options provide the functionality you're asking for? (I'd check myself but I don't have Minecraft on the laptop I'm using right now)

I'm writing this from the phone so I don't have how: /

**Comment by BakuQ** [comment]
> Can someone test the difference between disablePhysicsPlace and disablePhysicsUpdate and let me know? Also, do either of those options provide the functionality you're asking for? (I'd check myself but I don't have Minecraft on the laptop I'm using right now)

Overall, I'm delighted with your release, I've already tested a lot of these spigot forks (AtomSpigot, imanity spigot) and yours is the best optimized

**Comment by sadcenter** [comment]
> Can someone test the difference between disablePhysicsPlace and disablePhysicsUpdate and let me know? Also, do either of those options provide the functionality you're asking for? (I'd check myself but I don't have Minecraft on the laptop I'm using right now)

sure,
`disablePhysicsUpdate` is used when other blocks want to update themselves because, for example, someone broke 1 sand in a sand column
`disablePhysicsPlace` when a server wants to update placed block position because of physics.
And,
These options aren't providing what the author needs, cause he wants physics, but not its animations.

**Comment by BakuQ** [comment]
> @CyberFlameGO tak, istnieje możliwość wyłączenia fizyki całych bloków, ale nie animacji spadania. Myślę, że autorowi chodzi o dodanie opcji wyłączenia animacji spadających klocków
> 
>  2021-10-20.22-44-08.mp4

as in the movie, there is block physics but no animation

**Comment by tomasalves8** [comment]
I've got it working, I'll make a pr soon.

https://user-images.githubusercontent.com/15659074/141447366-eb9985c4-8942-46a0-b342-9ba52bd385e0.mp4

**Comment by tomasalves8** [comment]
I've got it working, I'll make a pr soon.

https://user-images.githubusercontent.com/15659074/141447366-eb9985c4-8942-46a0-b342-9ba52bd385e0.mp4
