### ISSUE TITLE
Citizens patch no longer needed

### ISSUE THREAD

**Issue by VytskaLT** [CobbleSword/NachoSpigot#221]
My PR on Citizens was merged which fixes the Netty incompatibility: https://github.com/CitizensDev/Citizens2/pull/2685

**Comment by Elierrr** [comment]
We should probably wait until Citizens makes a new release before removing it.

**Comment by Lucaskyy** [comment]
Yep, I agree with Elierrr. Should we do the same approach as with ProtocolLib? To leave the patch in there, and check if they have updated their Citizens and patch if it's too old.

**Comment by VytskaLT** [comment]
Why would anyone use old versions of ProtocolLib or Citizens? To me this just feels like bloat. I would just make the server not start up if a version of a plugin is unsupported. This way you no longer have to shade Javassist.

**Comment by Lucaskyy** [comment]
I do agree with that.

**Comment by Elierrr** [comment]
Close this issue @Lucaskyy
