### ISSUE TITLE
[Discussion] Which approach to take on optimizing packet sending

### ISSUE THREAD

**Issue by Lucaskyy** [CobbleSword/NachoSpigot#232]
I've been thinking about optimizing packet sending.
I have an idea for this, but I would like to hear input from others.

Currently, packets are as single-threaded as they could be. This is a huge bottleneck when you have a lot of players since hundreds of packets have to go through one single pipe.

My idea was to see if we can use OpenJDK's Project Loom to spawn a virtual thread for every player. So that every player has its own virtual packet thread, and keeps packet order.

Now, maybe we can check if the current JRE is Loom and use virtual threads if so, else fallback to single-threaded.

Reference:
  - https://wiki.openjdk.java.net/display/loom/Main
  - https://jdk.java.net/loom/

As for performance, according to OpenJDK, you can spawn millions of virtual threads. So creating a lot of virtual threads shouldn't be a problem, in case of a bot attack. I'd also like to use this for TNT, since currently if you explode TNT it uses a cached thread executor, which will spawn _n_ threads, where _n_ is the amount of TNT exploding currently.

What do you think? I would love to hear!

**Comment by andreasdc** [comment]
> I've been thinking about optimizing packet sending. I have an idea for this, but I would like to hear input from others.
> 
> Currently, packets are as single-threaded as they could be. This is a huge bottleneck when you have a lot of players, since hundreds of packets have to go through one single pipe.
> 
> My idea was to see if we can use OpenJDK's Project Loom to spawn a virtual thread for every player. So that every player has its own virtual packet thread, and keeps packet order.
> 
> Now, maybe we can check if the current JRE is Loom and use virtual threads if so, else fallback to single-threaded.
> 
> What do you think? I would love to hear!

Creating thread for every player will be more efficient?

**Comment by Lucaskyy** [comment]
Virtual threads, yes. OS threads, definitely not.

**Comment by sadcenter** [comment]
creating thread per player will screw the entire server performance. This "technique" was used by for instance aegis bungeecord fork and during attacks cpu could go up to 90% usage.

**Comment by Lucaskyy** [comment]
@sadcenter Is this the same for _**virtual**_ threads? They are a lot more performant, and according to what OpenJDK says, you can have millions of them at once. Since they aren't actual OS threads (which is more known as `new Thread()` in Java) but are virtual threads managed by the JRE.

**Comment by Lucaskyy** [comment]
@LewUwU @HeathLoganCampbell What do you think of this idea?

**Comment by andreasdc** [comment]
> creating thread per player will screw the entire server performance. This "technique" was used by for instance aegis bungeecord fork and during attacks cpu could go up to 90% usage.

You mean bungeecord with stolen code made by person who stole nachospigot's code and can't code by his own?

**Comment by Lucaskyy** [comment]
@andreasdc No offense, but please keep this out of this issue since it's off-topic.

**Comment by andreasdc** [comment]
> @andreasdc No offense, but please keep this out of this issue since it's off-topic.

That's what I want to have here too.

**Comment by sadcenter** [comment]
@Lucaskyy I haven't used virtual threads a lot but I think that's a great idea to test it

**Comment by Rastrian** [comment]
I haven't used virtual threads before, but as far I had seen some articles, doesn't feel like a bad idea.

**Comment by LewUwU** [comment]
> @LewUwU @HeathLoganCampbell What do you think of this idea?
Instead of using Virtual Threads, why not trying to use some netty tricks like Velocity did?

**Comment by Lucaskyy** [comment]
@LewUwU Could you elaborate on that?

**Comment by LewUwU** [comment]
https://github.com/VelocityPowered/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/network/ConnectionManager.java

**Comment by CyberFlameGO** [comment]
@Lucaskyy there's actually a Discussions feature in GitHub, and if you \(or someone else\) is able to enable it, it'd be a better solution than issues for conversations like these.
The toggle is [here](../settings) \(scroll down a bit\)

**Comment by Lucaskyy** [comment]
Closing this for now.

**Comment by andreasdc** [comment]
> Closing this for now.

Why?

**Comment by andreasdc** [comment]
> Closing this for now.

*insert sad music*

**Comment by HeathLoganCampbell** [comment]
Honestly Packet sending isn't worth optimising in most cases because packet receiving is worse in more cases

**Comment by andreasdc** [comment]
> Honestly Packet sending isn't worth optimising in most cases because packet receiving is worse in more cases

This netty system in general is pretty weird, I have big problems with sending packets, I think it's a good way to start too.

**Comment by andreasdc** [comment]
@HeathLoganCampbell @Lucaskyy That definetely is worth implementing, everything is really slow on high player count.

**Comment by Lucaskyy** [comment]
I understand, but in the end everything has to go through the Netty buffer. So do you really think it would help?

**Comment by andreasdc** [comment]
"Pack multiple messages into one "object" pass it to writeAndFlush(...) and have your own ChannelOutboundHandler that "decompose" this object into messages."
I think that's the only idea can give serious improvement. What do you think?
