### ISSUE TITLE
[Suggestion] Remove double raytrace

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#239]
PacketPlayInBlockPlace runs raytracing, after that you have another rayTrace. It would be nice to have this merged or optimized. :)
Raytracing is for sure inside Item and PlayerConnection classes.

**Comment by Rastrian** [comment]
Gonna fix it later.

**Comment by andreasdc** [comment]
> Gonna fix it later.

Any success?

**Comment by Rastrian** [comment]
> > Gonna fix it later.
> 
> Any success?

a little bit, i need more time for test it, mb next week.

**Comment by andreasdc** [comment]
@Rastrian can't wait :D

**Comment by andreasdc** [comment]
It's here
https://github.com/CobbleSword/NachoSpigot/blob/75f62419e1fceebdddd1a98f0bff94e5f7636728/NachoSpigot-Server/src/main/java/net/minecraft/server/ItemBucket.java#L25
&
https://github.com/CobbleSword/NachoSpigot/blob/75f62419e1fceebdddd1a98f0bff94e5f7636728/NachoSpigot-Server/src/main/java/net/minecraft/server/PlayerConnection.java#L847

**Comment by Lucaskyy** [comment]
Hmm? Why close?
