### ISSUE TITLE
Fastmath breaks projectiles

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#244]
Setting `enable-fastmath-cos-sin` to `true` causes projectiles such as bows, eggs and enderpearls to fly into wrong directions when shooting them in north or east direction.

**Comment by Rastrian** [comment]
Re-open this issue please.
As I said before, this kind of problem can be fixed, but not will work precisely.
Change the game behavior is one thing, *trigger* some sensitive system (like anticheats), is other.

**Comment by LewUwU** [comment]
For me this is a important bug fix since this makes minigames like SkyWars unusable

**Comment by Lucaskyy** [comment]
> For me this is a important bug fix since this makes minigames like SkyWars unusable

Then disable fastmath-cos-sin in the config. It's disabled by default.

**Comment by Rastrian** [comment]
> For me this is a important bug fix since this makes minigames like SkyWars unusable

Yeah, but it's not an critical bug, you can still use fastmath without sen/cos methods.
