### ISSUE TITLE
Incompatiblity/invisibility bug with ViaVersion

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#247]
Often on 1.17 when you join the server or you teleport someone to you from a long distance, you can't see him. Only relogging or going further than view distance helps. ViaVersion doesn't want to fix it, maybe you would look into that?

**Comment by Rastrian** [comment]
I think i know why this is hapenning, sportpaper does an ""fix"", that really doesn't fix it.
![image](https://user-images.githubusercontent.com/10719452/141935865-0031d655-9fbe-41d8-8801-73b0709c5ccb.png)

**Comment by andreasdc** [comment]
> I think i know why this is hapenning, sportpaper does an ""fix"", that really doesn't fix it. ![image](https://user-images.githubusercontent.com/10719452/141935865-0031d655-9fbe-41d8-8801-73b0709c5ccb.png)

I don't think that's the issue, but I will test without this patch tomorrow.

**Comment by Lucaskyy** [comment]
@andreasdc Any success?

**Comment by andreasdc** [comment]
> @andreasdc Any success?

Under testing, I think it should be clear in some time.

**Comment by andreasdc** [comment]
> @andreasdc Any success?

Still happening.

**Comment by andreasdc** [comment]
https://github.com/ViaVersion/ViaVersion/issues/2723#issuecomment-979313765
