### ISSUE TITLE
Error when patching plib

### ISSUE THREAD

**Issue by UnnamedWarrior** [CobbleSword/NachoSpigot#253]
[latest (24).log](https://github.com/CobbleSword/NachoSpigot/files/7551669/latest.24.log)

**Comment by tomasalves8** [comment]
@UnnamedWarrior I would ask that you follow the bug report template.
What version of Nacho are you using?

**Comment by UnnamedWarrior** [comment]
> @UnnamedWarrior I would ask that you follow the bug report template. What version of Nacho are you using?

I download it here
https://github.com/CobbleSword/NachoSpigot/actions/runs/1466933391

**Comment by Lucaskyy** [comment]
This shouldn't crash your server though? It should just continue, so what's the issue here?

Also, please follow the issue template next time instead of just ignoring it -_-
