### ISSUE TITLE
ConcurrentModificationException in tickEntities (possibly caused by tile entity tick changes)

### ISSUE THREAD

**Issue by Dysaido** [CobbleSword/NachoSpigot#255]
### Observed Behavior

Server crash

### Expected Behavior

Fawe world set

### Steps To Reproduce

Use fawe, and set air a big cube

### Plugin List

 Plugins (3): PlugMan, FastAsyncWorldEdit, WorldEdit

### Server Version

git-NachoSpigot-"0f441bb"

### Other

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2021.11.17. 21:50
Description: Exception ticking world entities

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at com.google.common.collect.Iterators$5.next(Iterators.java:553)
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1732)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:863)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:409)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:617)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
	at com.google.common.collect.Iterators$5.next(Iterators.java:553)
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1732)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayer['Dysaido'/3216, l='world', x=645,17, y=98,59, z=630,46](Dysaido at 645.1650408850857,98.58529666135665,630.4569713013278)]
	Chunk stats: ServerChunkCache: 877 Drop: 0
	Level seed: -3401886643437682598
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 188,00,64,00,94,00 - World: (188,64,94), Chunk: (at 12,4,14 in 11,5; contains blocks 176,0,80 to 191,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2020 game time, 2020 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 126687 (now: false), thunder time: 117486 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:863)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:409)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:617)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_311, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 421564016 bytes (402 MB) / 794296320 bytes (757 MB) up to 1864368128 bytes (1778 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	CraftBukkit Information: 
   Running: NachoSpigot version git-NachoSpigot-"0f441bb" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT) true
   Plugins: { PlugMan v2.2.5 com.rylinaux.plugman.PlugMan [rylinaux, Entity303], FastAsyncWorldEdit v19.11.13-5505943-1282-22.3.5 com.boydti.fawe.bukkit.BukkitMain [Empire92], WorldEdit v6.1.7;dd00bb1 com.sk89q.worldedit.bukkit.WorldEditPlugin [],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:278), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Timer-1: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING ForkJoinPool-4-worker-6: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], BLOCKED ForkJoinPool-1-worker-4: [com.boydti.fawe.object.changeset.FaweChangeSet$2$1.run(FaweChangeSet.java:266), java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source), java.util.concurrent.ForkJoinTask.doExec(Unknown Source), java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_8_R3.DedicatedServer$1.run(DedicatedServer.java:55)], TIMED_WAITING ForkJoinPool-4-worker-7: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_8_R3.CraftCrashReport.call(CraftCrashReport.java:29), net.minecraft.server.v1_8_R3.CrashReportSystemDetails.a(SourceFile:78), net.minecraft.server.v1_8_R3.CrashReport.h(CrashReport.java:127), net.minecraft.server.v1_8_R3.CrashReport.<init>(CrashReport.java:34), net.minecraft.server.v1_8_R3.CrashReport.a(CrashReport.java:312), net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:868), net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:409), net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724), net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:617), java.lang.Thread.run(Unknown Source)], BLOCKED ForkJoinPool-1-worker-5: [com.boydti.fawe.object.changeset.FaweChangeSet$2$1.run(FaweChangeSet.java:266), java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source), java.util.concurrent.ForkJoinTask.doExec(Unknown Source), java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], BLOCKED ForkJoinPool-1-worker-0: [com.boydti.fawe.object.changeset.FaweChangeSet$2$1.run(FaweChangeSet.java:266), java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source), java.util.concurrent.ForkJoinTask.doExec(Unknown Source), java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], RUNNABLE Server console handler: [org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method), org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:761), org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794), org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97), org.bukkit.craftbukkit.libs.jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:215), org.bukkit.craftbukkit.libs.jline.WindowsTerminal.access$000(WindowsTerminal.java:55), org.bukkit.craftbukkit.libs.jline.WindowsTerminal$1.read(WindowsTerminal.java:157), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2349), net.minecraft.server.v1_8_R3.DedicatedServer$2.run(DedicatedServer.java:81)], BLOCKED ForkJoinPool-1-worker-3: [com.boydti.fawe.object.changeset.FaweChangeSet$2$1.run(FaweChangeSet.java:266), java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source), java.util.concurrent.ForkJoinTask.doExec(Unknown Source), java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], BLOCKED ForkJoinPool-1-worker-1: [com.boydti.fawe.object.changeset.FaweChangeSet$2$1.run(FaweChangeSet.java:266), java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source), java.util.concurrent.ForkJoinTask.doExec(Unknown Source), java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.lang.ref.Reference.tryHandlePending(Unknown Source), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], WAITING Chunk I/O Executor Thread-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING User Authenticator #1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE ForkJoinPool-1-worker-7: [com.boydti.fawe.object.changeset.FaweStreamChangeSet$4.write(FaweStreamChangeSet.java:200), com.boydti.fawe.object.changeset.FaweStreamChangeSet.add(FaweStreamChangeSet.java:328), com.boydti.fawe.logging.rollback.RollbackOptimizedHistory.add(RollbackOptimizedHistory.java:99), com.boydti.fawe.object.changeset.FaweChangeSet$2$1.run(FaweChangeSet.java:313), java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source), java.util.concurrent.ForkJoinTask.doExec(Unknown Source), java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], WAITING ForkJoinPool-4-worker-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], RUNNABLE Attach Listener: [], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING ForkJoinPool-4-worker-3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 1: [java.lang.Object.wait(Native Method), com.boydti.fawe.object.FaweQueue.flush(FaweQueue.java:519), com.boydti.fawe.object.FaweQueue.flush(FaweQueue.java:504), com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:1316), com.sk89q.worldedit.extension.platform.CommandManager.handleCommandTask(CommandManager.java:496), com.sk89q.worldedit.extension.platform.CommandManager.handleCommandOnCurrentThread(CommandManager.java:417), com.sk89q.worldedit.extension.platform.CommandManager$3$1.run(CommandManager.java:535), com.boydti.fawe.object.FawePlayer.lambda$runAction$3(FawePlayer.java:345), com.boydti.fawe.object.FawePlayer$$Lambda$165/1468241457.run(Unknown Source), com.boydti.fawe.object.task.SimpleAsyncNotifyQueue.operate(SimpleAsyncNotifyQueue.java:25), com.boydti.fawe.object.task.AsyncNotifyQueue$1.run(AsyncNotifyQueue.java:15), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59), org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], BLOCKED ForkJoinPool-1-worker-2: [com.boydti.fawe.object.changeset.FaweChangeSet$2$1.run(FaweChangeSet.java:266), java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source), java.util.concurrent.ForkJoinTask.doExec(Unknown Source), java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE nioEventLoopGroup-3-1: [io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:445), io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365), io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357), io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365), io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357), io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365), io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357), io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365), io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919), io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166), io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719), io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655), io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Unknown Source)], RUNNABLE nioEventLoopGroup-2-1: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:810), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Unknown Source)], WAITING ForkJoinPool-4-worker-0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], RUNNABLE Signal Dispatcher: [], WAITING ForkJoinPool-4-worker-4: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], WAITING Timer-0: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING ForkJoinPool-4-worker-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], WAITING ForkJoinPool-4-worker-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_8_R3.FileIOThread.c(FileIOThread.java:52), net.minecraft.server.v1_8_R3.FileIOThread.run(FileIOThread.java:28), java.lang.Thread.run(Unknown Source)], TIMED_WAITING NachoSpigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:92)], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77), org.bukkit.craftbukkit.v1_8_R3.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25), java.lang.Thread.run(Unknown Source)], BLOCKED ForkJoinPool-1-worker-6: [com.boydti.fawe.object.changeset.FaweChangeSet$2$1.run(FaweChangeSet.java:266), java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source), java.util.concurrent.ForkJoinTask.doExec(Unknown Source), java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source), java.util.concurrent.ForkJoinPool.runWorker(Unknown Source), java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)],}
   Recent tasks from 1990-2020{FastAsyncWorldEdit:com.sk89q.worldedit.extension.platform.CommandManager$3@2027,FastAsyncWorldEdit:com.boydti.fawe.object.task.AsyncNotifyQueue$1@2028,}
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayer['Dysaido'/3216, l='world', x=645,17, y=98,59, z=630,46](Dysaido at 645.1650408850857,98.58529666135665,630.4569713013278)]
	Is Modded: Definitely; Server brand changed to 'NachoSpigot'
	Type: Dedicated Server (map_server.txt)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Lucaskyy** [comment]
@Rastrian Taking a quick look, it seems that your tile entity ticking change may have something to do with this.
Could you look into this sometime?

**Comment by Rastrian** [comment]
@Dysaido you can send me your nacho.yml config file?

**Comment by Dysaido** [comment]
The config is a default that the server generates. I didn't modify it.

**Comment by Elierrr** [comment]
Unable to reproduce

Plugins list:
```
Plugins (2): FastAsyncWorldEdit, WorldEdit
```

Version:
```
This server is running NachoSpigot version git-NachoSpigot-"514e752" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
Checking version, please wait...
You are running the latest version
```
