### ISSUE TITLE
Fast ops cause ops don't load from the file.

### ISSUE THREAD

**Issue by sadcenter** [CobbleSword/NachoSpigot#259]
### Observed Behavior

Ops checks should load from the file.

### Expected Behavior

Ops should load from the file.

### Steps To Reproduce

Enable `fast-operators` in configuration

### Server Version

git-NachoSpigot-baf5f2f

### Other

Fast ops are not working. Minecraft ops don't load instantly when an instance of `OpList` is created what causes there are no operators loaded yet, fast operators want to add every loaded operator when operators are not loaded yet(?)
IMO fast ops should be by default turned to true. 

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Elierrr** [comment]
> You have confirmed that you are NOT using a fork of NachoSpigot in any way. YOUR changes are not OUR faults.

**Comment by sadcenter** [comment]
Tested again on `git-NachoSpigot-"514e752"`. Same as above

**Comment by CyberFlameGO** [comment]
Replying to https://github.com/CobbleSword/NachoSpigot/issues/259#issuecomment-974561192

Honestly it should be re-worded anyway, both to be less aggressive and to confirm that the user has tested the issue on upstream

**Comment by Lucaskyy** [comment]
This is normal behavior! @HeathLoganCampbell coded fast ops like this intentionally.

**Comment by sadcenter** [comment]
Okay, so shouldn't it be renamed or commented with information?

**Comment by Lucaskyy** [comment]
Yes,

**Comment by Lucaskyy** [comment]
> Honestly it should be re-worded anyway, both to be less aggressive and to confirm that the user has tested the issue on upstream

@CyberFlameGO I agree. I was a little frustrated at the time when I added that (also the reason I added it in the first place), so that might've made it sound more aggressive.

**Comment by andreasdc** [comment]
> > Honestly it should be re-worded anyway, both to be less aggressive and to confirm that the user has tested the issue on upstream
> 
> @CyberFlameGO I agree. I was a little frustrated at the time when I added that (also the reason I added it in the first place), so that might've made it sound more aggressive.

Chill
