### ISSUE TITLE
Knockback.yml doesnt load correcly

### ISSUE THREAD

**Issue by UnnamedWarrior** [CobbleSword/NachoSpigot#264]
### Observed Behavior

Knockback yml »
![Screenshot_2021-11-23-11-12-53-69_8533ed6bac78e90ce765f82a6ab353f9](https://user-images.githubusercontent.com/88706372/143530069-c12c324a-b8d4-427b-89c2-efa167181aa7.jpg)

Ingame »
![Screenshot_2021-11-23-10-48-41-65_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/88706372/143530125-9515e057-1bea-405b-8bc2-c81de3a1453b.jpg)

### Expected Behavior

Egg vertical kb should be at 0.25

### Steps To Reproduce

Idk

### Plugin List

I don't think plugin will cause the issue

### Server Version

Well i downloaded the jar here
https://github.com/CobbleSword/NachoSpigot/actions/runs/1497029226

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Elierrr** [comment]
Did you change knockback.yml while the server was running?

**Comment by UnnamedWarrior** [comment]
No? When i start the server for the first time i create a new profile and stop the server then configure the projectile kb values on the knockback.yml file then start the server

**Comment by UnnamedWarrior** [comment]
> Did you change knockback.yml while the server was running?

No? When i start the server for the first time i create a new profile and stop the server then configure the projectile kb values on the knockback.yml file then start the server
