### ISSUE TITLE
Slow packet sending

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#270]
### Describe the feature

![image](https://user-images.githubusercontent.com/82218780/143937740-1cea7dc1-2a0a-41ae-b2f3-fcb7a72cce29.png)

### Technical implementation

Why don't we remove usage of getProtocolForPacket and set it to every packet once and then just take it? getProtocolForPacket and setProtocol are more expensive than sending actual packet/passing it to netty.

### Agreements

- [X] You have confirmed that this feature does not yet exist in the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this feature.

**Comment by andreasdc** [comment]
Also 13 days ago Paper released this patch: https://github.com/PaperMC/Paper/blob/master/patches/server/0310-Optimize-Network-Manager-and-add-advanced-packet-sup.patch

**Comment by LewUwU** [comment]
> Also 13 days ago Paper released this patch: https://github.com/PaperMC/Paper/blob/master/patches/server/0310-Optimize-Network-Manager-and-add-advanced-packet-sup.patch

That will not help too much

**Comment by LewUwU** [comment]
> ### Describe the feature
> ![image](https://user-images.githubusercontent.com/82218780/143937740-1cea7dc1-2a0a-41ae-b2f3-fcb7a72cce29.png)
> 
> ### Technical implementation
> Why don't we remove usage of getProtocolForPacket and set it to every packet once and then just take it? getProtocolForPacket and setProtocol are more expensive than sending actual packet/passing it to netty.
> 
> ### Other
> _No response_
> 
> ### Agreements
> * [x]  You have confirmed that this feature does not yet exist in the latest version of NachoSpigot.
> * [x]  You have confirmed that there aren’t any issues open regarding this feature.

If you can test that something like ProtocolLib or minecraft itself doesn't crash and works correctly, fine 😳

**Comment by LewUwU** [comment]
> I don't use PLIb, as you can see getProtocolForPacket is on top of packet sending, which is not acceptable.

You're saying that we should remove the usage of getProtocolForPacket without considering if it would break plugins, that's what im talking

**Comment by andreasdc** [comment]
> > I don't use PLIb, as you can see getProtocolForPacket is on top of packet sending, which is not acceptable.
> 
> You're saying that we should remove the usage of getProtocolForPacket without considering if it would break plugins, that's what im talking

Do whatever you want with some weird plugins, I'm reporting big performance leak in this method, it can be done without having any hashmap as I believe.

**Comment by LewUwU** [comment]
> > > I don't use PLIb, as you can see getProtocolForPacket is on top of packet sending, which is not acceptable.
> > 
> > 
> > You're saying that we should remove the usage of getProtocolForPacket without considering if it would break plugins, that's what im talking
> 
> Do whatever you want with some weird plugins, I'm reporting big performance leak in this method, it can be done without having any hashmap as I believe.

Then the changes that you proposed aren't acceptable. Nacho focus on performance improvements, new api and all these things but not on breaking plugins

**Comment by andreasdc** [comment]
> s

I don't know how can this break plugins, but if you want to change slow methods for weird plugins do it, it will be the best to make this change to have better performance.

**Comment by Lucaskyy** [comment]
Some code was left in there for compatibility with plugins such as ProtocolLib.
I could definitely make an EnumProtocol interface, then have one implementing the current one and a completely new one from scratch. But IMO, that's a time waste, since pretty much everyone uses ProtocolLib. I'm not going to spend hours or days for a couple of people to use it.

I'm going to close this for now, but I *might* look into it later on.
