### ISSUE TITLE
Can't use Nacho's API

### ISSUE THREAD

**Issue by Elierrr** [CobbleSword/NachoSpigot#274]
### Observed Behavior

Gradle fails to find Nacho's API

### Expected Behavior

Gradle successfully builds

### Steps To Reproduce

1. Clone https://github.com/Elierrr/NachoTestPlugin
2. Edit build.gradle.kts:
- Uncomment line 6
- Uncomment line 11
- Comment line 12
3. Run `./gradlew build` (Linux/Mac OS) or `gradlew build` (Windows)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Lucaskyy** [comment]
Yeah jitpack is an absolute pain in the ass right now, seems like I'll have to fix it.

**Comment by Elierrr** [comment]
Fixed, the problem was that jitpack couldn't find the commit in the BuildData submodule since it wasn't on a branch but now it's fixed.
