### ISSUE TITLE
Double block change packet

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#278]
### Observed Behavior

After placing water there are 2 block change packets coming from PlayerChunkMap. Is it the right behaviour?

### Expected Behavior

1 block changed = 1 block update

### Steps To Reproduce

Place a water of bucket.

### Server Version

-

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Lucaskyy** [comment]
I don't appreciate being joked on.
