### ISSUE TITLE
Double block change packet

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#279]
### Describe the feature

After placing water there are 2 block change packets coming from PlayerChunkMap. Is it the right behaviour?
Maybe you could investigate to see if that should happen?
I don't know why https://github.com/CobbleSword/NachoSpigot/issues/278 was closed, but that's not a joke and this causes visual (or other) bugs, while impacting performance.
If I'm wrong please tell me. 

### Agreements

- [X] You have confirmed that this feature does not yet exist in the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this feature.

**Comment by andreasdc** [comment]
https://github.com/CobbleSword/NachoSpigot/issues/277#issuecomment-987052695
Don't treat people like gods, from a quick look to Paper 1.17 I don't see similar block updates.

**Comment by andreasdc** [comment]
It's messed up, but has some kind of logic in it. If you want you can reopen it, but I think it's ok.

**Comment by Lucaskyy** [comment]
It wasn't that your issue was a joke, it's about the fact that I lock the issue since it's to heated and then you just create another issue like nothing?

**Comment by andreasdc** [comment]
I don't even want to reply to this

**Comment by Lucaskyy** [comment]
Sigh.. be my guest then.
