### ISSUE TITLE
Cannot craft anvils

### ISSUE THREAD

**Issue by TheZocki** [CobbleSword/NachoSpigot#290]
### Observed Behavior

Hey! I am currently using NachoSpigot in 1.8 and it doesn't let me craft anvils but I try with another fork and it does let me, so I don't really know what to do right now. 

### Expected Behavior

The anvil's crafting works correctly.

### Steps To Reproduce

https://streamable.com/b5yjhs

### Plugin List

![image](https://user-images.githubusercontent.com/88005088/145716938-a3827f20-4cd5-44c2-9c1e-465264fc2642.png)

### Server Version

![image](https://user-images.githubusercontent.com/88005088/145716952-54043e8b-ca93-4f6f-b921-8f8d3ced9d1a.png)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Lucaskyy** [comment]
Sorry but just what the hell happened that caused anvils to be not craftable, lol.
I'll take a look at it.

**Comment by TheZocki** [comment]
Thank you so much!

**Comment by TheZocki** [comment]
![image](https://user-images.githubusercontent.com/88005088/145717141-4c7993a6-7cba-46d4-a059-60c2f4f25488.png)

**Comment by Elierrr** [comment]
I think I know why this is happening, I'll make a PR.

**Comment by TheZocki** [comment]
Thank you very much :D
