### ISSUE TITLE
Player statistics are not working properly

### ISSUE THREAD

**Issue by DerStandard** [CobbleSword/NachoSpigot#293]
### Observed Behavior

Player statistics shows random numbers (100 - 999)

### Expected Behavior

The right statistics of the player

### Steps To Reproduce

e.g.

int diamonds = player.getStatistic(Statistic.MINE_BLOCK, Material.DIAMOND_ORE);

### Server Version

latest commit

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Lucaskyy** [comment]
Could you send a pastebin with your nacho.yml?

**Comment by DerStandard** [comment]
https://pastebin.com/VV8VML68

**Comment by Elierrr** [comment]
I'm unable to reproduce this, however I am getting a different issue. (#295)

**Comment by Lucaskyy** [comment]
No response, closing this for now. If it still occurs, reopen the issue.
