### ISSUE TITLE
Block Bug

### ISSUE THREAD

**Issue by Pascalpex** [CobbleSword/NachoSpigot#30]
If you modify the world, unload the chunks and load them again, the changes are no longer visible.
Server Information:
- Java 15.0.2 64-Bit
- Windows 10
- Clean install without any plugins

Video: https://youtu.be/Imt2ilR6h9g
This happens on the latest stable and dev build.

**Comment by Lucaskyy** [comment]
This sounds fun, sigh...

I will take a look at this >.<

**Comment by Sneakometer** [comment]
Same here.
Just place some blocks, rejoin or /kill and the blocks are invisible client side.

Java 8
Debian 10

**Comment by Lucaskyy** [comment]
I see, so after some testing, I found that if you place blocks in a single chunk it doesn't get saved. But if you place blocks in multiple chunks then it does get saved.

**Comment by Lucaskyy** [comment]
I should've known haha, this is a 1.9 patch so that's why this doesn't work and it looked good to me so I pushed it to stable. I will remove it, and test to see if that really was the issue.

**Comment by Lucaskyy** [comment]
Even though what I thought was wrong wasn't true, I did fix the issue.
