### ISSUE TITLE
Crash when tryinmg to use protocol support for servers running minecraft 1.8

### ISSUE THREAD

**Issue by ITzTravelInTime** [CobbleSword/NachoSpigot#301]
### Observed Behavior

The server crashes with this error messange:

`java.lang.ExceptionInInitializerError
[18:52:50 WARN]:     at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:24)
[18:52:50 WARN]:     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:329)
[18:52:50 WARN]:     at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:207)
[18:52:50 WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:562)
[18:52:50 WARN]:     at java.lang.Thread.run(Thread.java:748)
[18:52:50 WARN]: Caused by: java.lang.NoSuchFieldException: h
[18:52:50 WARN]:     at java.lang.Class.getDeclaredField(Class.java:2070)
[18:52:50 WARN]:     at protocolsupport.protocol.ServerBoundPacket.<init>(ServerBoundPacket.java:84)
[18:52:50 WARN]:     at protocolsupport.protocol.ServerBoundPacket.<clinit>(ServerBoundPacket.java:45)
[18:52:50 WARN]:     ... 5 more`

more info in the log file:

[latest.log](https://github.com/CobbleSword/NachoSpigot/files/7729562/latest.log)
 

### Expected Behavior

The server should have started as usual and protocol support should be working. It worked with the og taco spigot for 1.8.8 and with the latest spigot 1.8.8 builds version that features fixes for log4j.

### Steps To Reproduce

Make a test server using java 8 on a macOS intel host (tested on big sur and high sierra, should be reproduceable with linux), then use protocollib + protocol support for server running 1.8.8 (https://protocol.support/old/).

### Plugin List

 TimTheEnchanter, Essentials, EssentialsProtect, EssentialsChat, GroupManager, ClearLag, EssentialsAntiBuild, iConomy, DisableCommands, Chairs, LagMonitor, Lockette, Vault, EssentialsSpawn, ProtocolSupport, Multiverse-Core, ProtocolLib, Citizens, SkinsRestorer, Factions, ChestShop, AuthMe, ClientStats.

### Server Version

Latest commit dec. 16th 2021.

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Lucaskyy** [comment]
Ah, I see. I recoded the EnumProtocol some time ago, which seems to break ProtocolSupport. For now if possible, use ProtocolLib instead.

**Comment by ITzTravelInTime** [comment]
Protocol support is the plugin that allows me to let people using the powerpc minecraft project join the server, and it requires protocol lib in order to work, so i think the only good solution here is make a custom protocol support fork right?

Is there anyway this can be fixed in nacho?

**Comment by Ytnoos** [comment]
> Protocol support is the plugin that allows me to let people using the powerpc minecraft project join the server, and it requires protocol lib in order to work, so i think the only good solution here is make a custom protocol support fork right?
> 
> Is there anyway this can be fixed in nacho?

Why would you use ProtocolSupport which only supports the latest versions while ViaRewind is still updated?
