### ISSUE TITLE
console spaming

### ISSUE THREAD

**Issue by Ramgaming** [CobbleSword/NachoSpigot#304]
### Observed Behavior

https://mclo.gs/PtFnm2z
spam in my console idk why

### Expected Behavior

it should be not 

### Steps To Reproduce

i dnt much ideas about this kind of stuff i m justing open this issue bcz someone said on nachos dc to open issue

### Server Version

This server is running NachoSpigot version git-NachoSpigot-625c213 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Lucaskyy** [comment]
What plugins are you running? And NPC plugins, or StrikePractice? Tell us more about your server environment and how to reproduce your issue. Also, when does this issue occur?

**Comment by Ramgaming** [comment]
> 

https://www.toptal.com/developers/hastebin/qalotenoka.csharp
this one is big spam maybe its help you

and here is my plugins list

**Plugins** (20): WorldEdit, VoidGen, PlaceholderAPI, ViaVersion, CommandPanels, SquidGame, MobDisabler, WorldGuard, Multiverse-Core, ProtocolLib, LuckPerms, Citizens, Vulcan, DeluxeHub, BungeeGuard, KitPvP, Arcade, GadgetsMenu, Pl-Hide-Pro, TAB

**Comment by Elierrr** [comment]
This issue is caused by when an entity is hurt thorns, and also weirdly the entity disappears after being hit.
