### ISSUE TITLE
Remove pluginmetrics

### ISSUE THREAD

**Issue by Reed3411** [CobbleSword/NachoSpigot#305]
### Describe the feature

I suggest you remove plugin metrics from NachoSpigot, it doesn't even exist anymore so there's no point in having it anyway.

### Technical implementation

I know SportPaper (https://github.com/Electroid/SportPaper) has a patch for this but there are so many patches its hard to find, I think its buried inside a patch with a name that doesn't suggest it disables PluginMetrics. - There a lot of other useful patches in SportPaper that people might want to consider putting in some version into NachoSpigot, for example (https://github.com/Electroid/SportPaper/blob/master/patches/api/0082-Server-suspend-API.patch) I think is also a pretty neat idea.

### Agreements

- [X] You have confirmed that this feature does not yet exist in the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this feature.

**Comment by crafter23456** [comment]
You think removing the BukkitMirrorTest.java doesnt lead to incompatibles? In my next PR I can remove both (+ PluginMetrics), but idk with the API. Could be a nice addon for ppl which code plugins by themself but for all others unused.
