### ISSUE TITLE
Nacho Spigot not building

### ISSUE THREAD

**Issue by PlunginPlugins** [CobbleSword/NachoSpigot#311]
### Observed Behavior

When I try to compile into a jar, i get this message:

`[ERROR] Failed to execute goal on project nachospigot: Could not resolve dependencies for project dev.cobblesword.nachospigot:nachospigot:jar:1.8.8-R0.2-SNAPSHOT: Could not transfer artifact org.spigotmc:minecraft-server:jar:1.8.8-SNAPSHOT from/to elmakers-repo (https://maven.elmakers.com/repository/): GET request of: org/spigotmc/minecraft-server/1.8.8-SNAPSHOT/minecraft-server-1.8.8-SNAPSHOT.jar from elmakers-repo failed: javax.crypto.AEADBadTagException: Tag mismatch! -> [Help 1]`

### Expected Behavior

I was expecting it to compile to jar

### Steps To Reproduce

1. Clone the repo
2. run mvn clean install

### Plugin List

Build issue

### Server Version

Build issue

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Elierrr** [comment]
Try again, I'm unable to reproduce this.

**Comment by Lucaskyy** [comment]
@Elierrr You sure it's not cached in your Maven repository cache?

**Comment by Elierrr** [comment]
> @Elierrr You sure it's not cached in your Maven repository cache?

I removed the minecraft-server dependency from my cache before testing it.

**Comment by Lucaskyy** [comment]
Probably some sort of TLS error.
Just try again.
