### ISSUE TITLE
Player#hidePlayer() not persistent

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#314]
### Observed Behavior

When hiding players from each other using the Bukkit Player API, the Player will be visible again when teleporting far away and then back.

### Expected Behavior

To stay invisible

### Steps To Reproduce

Hide players from each other, teleport far away and then back.

### Server Version

2cefae4

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Marijn2341** [comment]
Hi Sneakometer,

This isn't a bug in NachoSpigot.
I tried the same thing like you described in the issue. But everything worked fine.

You are probably using the API incorrectly.
Can you send the code where you hide a player?
