### ISSUE TITLE
Have compatibility problems with plugin BKCommonLib,TrainCarts and maybe more

### ISSUE THREAD

**Issue by HowardZHY** [CobbleSword/NachoSpigot#317]
### Observed Behavior

[latest.log](https://github.com/CobbleSword/NachoSpigot/files/7785068/latest.log)
I cannot join the server. The client said Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexDut0fBoundsException:readerIndex(1) + length(1) exceeds uriterIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1) and console was spamming error.

### Expected Behavior

There's no bug with these plugins on Tacospigot , but on Nacho. I hope to fix plugin compatibility problems.

### Steps To Reproduce

Use latest version of plugins: BKCommonLib, Train Carts, Viaversion and 1.8.8 version plugin Protocol Support.
Use any client to join, I tested with 1.8 and 1.12.2

### Plugin List

Plugins (29): [0;32;1mWarpMagic[0;37;1m, [0;32;1mCorpseReborn[0;37;1m, [0;32;1mPermissionsDisable[0;37;1m, [0;32;1mBleed[0;37;1m, [0;32;1mClearLag[0;37;1m, [0;32;1mCrackShot[0;37;1m, [0;32;1mCrazyCore[0;37;1m, [0;32;1mChairs[0;37;1m, [0;32;1mTpr[0;37;1m, [0;32;1mCitizens[0;37;1m, [0;32;1mLANBroadcaster[0;37;1m, [0;32;1mAntiCmds[0;37;1m, [0;32;1mResidence[0;37;1m, [0;32;1mBetterPing[0;37;1m, [0;32;1mCS-CoreLib[0;37;1m, [0;32;1mMiaoLog4j2Fix[0;37;1m, [0;32;1mProtocolSupport[0;37;1m, [0;32;1mSimpleSit[0;37;1m, [0;32;1mCrazyLoginFilter[0;37;1m, [0;32;1mSentry[0;37;1m, [0;32;1mSlimefun[0;37;1m, [0;32;1mViaVersion[0;37;1m, [0;32;1mViaRewind[0;37;1m, [0;32;1mProtocolLib[0;37;1m, [0;32;1mSkinsRestorer[0;37;1m, [0;32;1mClientDetector[0;37;1m, [0;32;1mBKCommonLib[0;37;1m, [0;32;1mColorMOTD[0;37;1m, [0;32;1mTrain_Carts

### Server Version

NachoSpigot1.8.8

### Other

plz fix it

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by HowardZHY** [comment]
the version is the release on Dec23

**Comment by HeathLoganCampbell** [comment]
@HowardZHY Please try [BurritoSpigot ](https://github.com/CobbleSword/BurritoSpigot)instead

**Comment by HowardZHY** [comment]
> @HowardZHY Please try [BurritoSpigot ](https://github.com/CobbleSword/BurritoSpigot)instead

All my plugins works well on Burrito.
 And I will keep watching Nacho, because there's more custom options and patches.

**Comment by sadcenter** [comment]
It might be an issue caused by netty update in NachoSpigot.
(If you are the developer of these plugins or you have contact with the developer, tell him that he has to shade the netty he is using and relocate it, or simply update to the latest version)

**Comment by Elierrr** [comment]
> It might be an issue caused by netty update in NachoSpigot.

It looks like an issue with BKCommonLib and the fastutil update

**Comment by sadcenter** [comment]
NVM, the error is thrown by a client, I thought that is an exception in the server

**Comment by HowardZHY** [comment]
> NVM, the error is thrown by a client, I thought that is an exception in the server

Still have that problem with latest version. Check this
[latest.log](https://github.com/CobbleSword/NachoSpigot/files/7894518/latest.log)

**Comment by HowardZHY** [comment]
There's no error on client's log.

**Comment by HowardZHY** [comment]
[latest.log](https://github.com/CobbleSword/NachoSpigot/files/7901635/latest.log)
With latest version today. Players can't join.

**Comment by HowardZHY** [comment]
Still have problem with Train Carts.
[latest.log](https://github.com/CobbleSword/NachoSpigot/files/7965327/latest.log)
With latest version.

**Comment by HowardZHY** [comment]
Reported this bug to TrainCarts's author.

**Comment by HowardZHY** [comment]
Latest build of BKCommonlib fixed today.

**Comment by CyberFlameGO** [comment]
Sweet!
