### ISSUE TITLE
Players get kicked for "wrong capacity"

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#32]
When switching to nacho all players get kicked for "wrong capacity".
Only onw player can be connected at a time. When a second one joins, both get kicked.
Tried both the stable and dev build.

Seems to be related with our tablist/scoreboard plugin. At least its working without it. But on older nacho versions and paper it's not causing issues.
There are no exceptions in console. Just
`[01.05 22:05:36.234] INFO: [Lobby-1] [22:05:12 INFO]: Sneako lost connection: Wrong capacity!`

Nacho devbuild
Java 8
Debian 10

**Comment by LewUwU** [comment]
This is caused by the AntiCrash implementation that was added by Sculas
