### ISSUE TITLE
Update guava to latest

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#322]
### Describe the feature

Update all google libraries to it's latest version, currently guava 31.0.1 and gson 2.8.9 to achieve higher security, allow plugins to use new libary features and better performance.

### Technical implementation

Update dependencies in pom.yml and fix compilation errors in
- CraftServer
- BaseBlockPosotion
- BlockStateList
- BlockState
- PacketPlayOUtPlayerInfo
- TripwireHook
- and EntitySlice

### Other

This might break compatibility with rare plugins that deeply interact with nms.
This should be properly tested before publishing to the official Nacho builds.

### Agreements

- [X] You have confirmed that this feature does not yet exist in the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this feature.

**Comment by Elierrr** [comment]
> * CraftServer
> * BaseBlockPosotion
> * BlockStateList
> * BlockState
> * PacketPlayOUtPlayerInfo
> * TripwireHook
> * and EntitySlice

It definitely isn’t just those classes, there are other classes that use guava/gson that aren’t imported because we don’t make changes to them.
