### ISSUE TITLE
Blank lines between some messages

### ISSUE THREAD

**Issue by DrakMC** [CobbleSword/NachoSpigot#327]
### Observed Behavior

I noticed that there are blank lines in the log between some of the messages. For example, when someone writes something in chat.

### Expected Behavior

Blank lines should not be displayed.

### Steps To Reproduce

1. Turn on the server with NachoSpigot
2. Send something in chat
3. There is a space before the messages in the log

### Server Version

[12:18:21 INFO]: This server is running NachoSpigot version git-NachoSpigot-"c901193" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
You are running the latest version

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Elierrr** [comment]
I cannot reproduce this. This is most likely an issue with your console.

**Comment by DrakMC** [comment]
It happens to me. I'm using pterodactyl panel. It's not caused by the panel because I have blank lines in log file as well.

My log file: https://pastebin.com/raw/QXQDjbkb
Panel: https://i.imgur.com/B5nvUVM.png
In-game: https://i.imgur.com/p96K7nH.png

**Comment by DrakMC** [comment]
It looks like it's fixed in new version. Thanks

**Comment by DrakMC** [comment]
I updated it to the newest version and it still doesn't work.

**Comment by crafter23456** [comment]
Actually thats caused by any java version above 8.

**Comment by sadcenter** [comment]
well, it doesn't happen on my server, which is also on the pterodactyl panel
I'm using `ghcr.io/pterodactyl/yolks:java_17` (`java 17`)

**Comment by DrakMC** [comment]
I'm using the same image and the problem persists.

**Comment by crafter23456** [comment]
> I'm using the same image and the problem persists.

Try with Java 8 for testing purpose only. with java 8 i hadnt the problem but with java 11 and up.

**Comment by crafter23456** [comment]
> I'm using the same image and the problem persists.

Okay, with Java 11 the problem isnt there. I switched to Java 14 and then it happens. My bad memories. I tracked your problem down, that LOGGER.info doesnt write empty lines beneath, only System.out.println(). Yeah for nachospigot we can make a dump way to change the new few (guess 4) System.out.println to LOGGER.info but that isnt purposeful because then all plugins still writes empty lines. So the problem needs to be taken on the roots, System.out.println.

**Comment by LewUwU** [comment]
Just change the sysout calls to Logger calls

**Comment by crafter23456** [comment]
yeah i make a PR later, almost finished

**Comment by HowardZHY** [comment]
Burrito also have this on console ?
