### ISSUE TITLE
Block bugs inside of Player with higher Version

### ISSUE THREAD

**Issue by byCrypex** [CobbleSword/NachoSpigot#33]
Java: 1.11
Plugins: ViaVersion

Wenn man mit einer höheren Version als der 1.8 einen Block unter sich platziert, wird dieser platziert und man bugt zur Seite. Dadurch kann der Spieler unter anderem in der Wand sterben.

**Comment by Lucaskyy** [comment]
I'm not German, but from my understanding, you are using the latest version of NachoSpigot with ViaVersion and you are encountering this issue?

If you are not on the latest version of Nacho, try updating and let me know if you still have this issue.

**Comment by Lucaskyy** [comment]
Please make sure you are using the latest stable version of NachoSpigot because I am not able to reproduce your issue at this moment. Please re-open if you still have this issue when using the latest version.
