### ISSUE TITLE
Tellraw loss some message parts

### ISSUE THREAD

**Issue by caoli5288** [CobbleSword/NachoSpigot#330]
### Observed Behavior

Tellraw loss some message parts.  See `Steps To Reproduce`

### Expected Behavior

See `Steps To Reproduce`

### Steps To Reproduce

Run commands below
> tellraw @a ["",{"text":"§6[§aworld§6]","clickEvent":{"action":"run_command","value":"/tpa y1wan"},"hoverEvent":{"action":"show_text","value":"§6当前所在位置:\n§6世界: §dworld\n§6坐标: §aX:-136 Y: 64 Z: -183\n\n§c点击即可TP我!"}},{"text":"§fy1wan","clickEvent":{"action":"suggest_command","value":"/m y1wan"},"hoverEvent":{"action":"show_text","value":"§6玩家名称: §by1wan\n\n§c点击与我聊天"}},{"text":": "},{"text":"aaa"}]

Shown 
![图片](https://user-images.githubusercontent.com/3120587/149747000-a7b474e6-7751-4ab5-9d96-207b13bfa3c1.png)
 in nacho, it's wrong.

Shown 
![图片](https://user-images.githubusercontent.com/3120587/149747112-2cc1fc6e-dc41-43d1-9863-9f25772406d4.png)
in origin spigot, it's okay.

### Plugin List

Plugins (13): SimpleORM, PlaceholderAPI, iConomy, ViaVersion, Vault, VexView, LogManager, ProtocolLib, VexWrapper, Teams2, CMILib, Residence, QuickShop

### Server Version

This server is running NachoSpigot version git-NachoSpigot-"c901193" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by sadcenter** [comment]
https://github.com/CobbleSword/NachoSpigot/commit/200fb393a8cfe5107313948b531bfedd354fe9fd
```java
IChatBaseComponent var5 = ChatSerializer.a(var4);
```
Seems that the security patch from SportPaper could have messed up.

**Comment by Elierrr** [comment]
> [200fb39](https://github.com/CobbleSword/NachoSpigot/commit/200fb393a8cfe5107313948b531bfedd354fe9fd)
> 
> ```java
> IChatBaseComponent var5 = ChatSerializer.a(var4);
> ```
> 
> Seems that the security patch from SportPaper could have messed up.

After reverting this commit, the text shows correctly so it is caused by this commit.
