### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Hyronymos1337** [CobbleSword/NachoSpigot#332]
### Observed Behavior

Random crashes

### Expected Behavior

https://privatebin.net/?f0170b0f66f79665#4VhhukSrY2JFpEpaGJ6j9cWQRDeTMjYEii9TtVRbrGFw

### Steps To Reproduce

idk

### Server Version

latest nachospigot

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by sadcenter** [comment]
plugin list?

**Comment by Elierrr** [comment]
The crash log has expired, please repost it.

**Comment by Lucaskyy** [comment]
@Hyronymos1337 Please repost the crash log.

**Comment by refractored** [comment]
Stale ticket?

**Comment by Lucaskyy** [comment]
If this issue still occurs, please reopen it and repost the crash log.
