### ISSUE TITLE
Implement starlight

### ISSUE THREAD

**Issue by sadcenter** [CobbleSword/NachoSpigot#334]
### Describe the feature

Implement https://github.com/PaperMC/Starlight light system

### Technical implementation

https://github.com/PaperMC/Paper/blob/master/patches/server/0807-Rewrite-the-light-engine.patch
https://github.com/PaperMC/Paper/blob/master/patches/server/0808-Always-parse-protochunk-light-sources-unless-it-is-m.patch
Here's how the author of starlight did this

### Other

I know it's kinda difficult to implement starlight on 1.8.8 but the performance is worth it. I don't think there is a even single fork that has patched it. 

### Agreements

- [X] You have confirmed that this feature does not yet exist in the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this feature.

**Comment by caoli5288** [comment]
WTF a 5000+ lines patch?!

**Comment by sadcenter** [comment]
Most of the patch is just https://github.com/PaperMC/Starlight source code, which you can download

**Comment by HeathLoganCampbell** [comment]
I don't believe this patch applies to 1.8 due to the world format being different

**Comment by LewUwU** [comment]
> I don't believe this patch applies to 1.8 due to the world format being different

(also the light engine in 1.16 is a lot of interfaces & abstract classes)

**Comment by MWHunter** [comment]
Starlight's algorithms are more efficient than 1.8's design, but 1.8 has a much cleaner light engine than 1.14's mess so the difference might not be worth the effort.

**Comment by sadcenter** [comment]
oh, okay then. My friend told me that the result will be worth it
