### ISSUE TITLE
Blockhit glitch

### ISSUE THREAD

**Issue by InfiniteAura** [CobbleSword/NachoSpigot#347]
### Observed Behavior

Players not un-blocking their swords after releasing right mouse button.

### Expected Behavior

The players should stop blockhitting after releasing RMB.

### Steps To Reproduce

https://youtu.be/NooH704kMGo

### Server Version

![image](https://user-images.githubusercontent.com/79237684/153217188-17d43f66-98a2-4d68-b61e-ce5607eb3272.png)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [x] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by HowardZHY** [comment]
Using ForkedNacho ??

**Comment by InfiniteAura** [comment]
> Using ForkedNacho ??

![image](https://user-images.githubusercontent.com/79237684/153739157-ff68e31b-2a2b-4d3c-b5ab-3b93353a58e9.png)
