### ISSUE TITLE
Weird channel pipeline behavior with PacketEvents 2.0

### ISSUE THREAD

**Issue by Lucaskyy** [CobbleSword/NachoSpigot#356]
### Observed Behavior

NachoSpigot 1.8:
[pe-connection-initializer-grimac, MinecraftPipeline#0, PreChannelInitializerModern_v1_8$1#0, DefaultChannelPipeline$TailContext#0]

### Expected Behavior

PaperSpigot 1.8:
[PreChannelInitializerModern_v1_8$1#0, timeout, legacy_query, splitter, decoder, prepender, encoder, packet_handler, DefaultChannelPipeline$TailContext#0]

### Steps To Reproduce

Unknown, needs to be edited.

### Server Version

Assuming latest version as of now, needs to be edited.

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

**Comment by Lucaskyy** [comment]
Thanks for linking the issue.

I still don't get it though why that happens, best bet is trying to compare the source code and look for potential mistakes.

Like I said on Discord, a *child handler* shouldn't be listed as a *channel pipeline*... I think?

**Comment by MWHunter** [comment]
Minimally reproducible with https://www.spigotmc.org/resources/grim-anticheat.99923/
No other plugins are required.  PacketEvents 2.0 is shaded in the jar.

When it fails to inject it will give you the debug message listing the pipeline

**Comment by MWHunter** [comment]
Retrooper has fixed this, will be merged into PacketEvents after ProtocolLib fixes their injector

**Comment by retrooper** [comment]
Well I think I have, once I have time I will test it.

**Comment by retrooper** [comment]
Or even more likely when ProtocolLib pushes their 5.0.0 dev builds.

**Comment by retrooper** [comment]
Although this wasn't an issue on our end, similarly to ViaVersion, we now included a Paper injector which uses the Paper 
```java
ChannelInitializeListenerHolder.addListener(Key, ChannelInitializeListener)
```
We now therefore support NachoSpigot. I guess we can close the issue now.

**Comment by Elierrr** [comment]
@Lucaskyy ^^
