### ISSUE TITLE
Viaversion and Protocol Support not working together

### ISSUE THREAD

**Issue by HowardZHY** [CobbleSword/NachoSpigot#357]
### Observed Behavior

When using both Viaversion and Protocol Support on Nacho, higher version clients aren't able to join.
There's only "Unsupported protocol xxx" on client , and no error and no msg about player on console.

### Expected Behavior

Viaversion and Protocol Support should work together, just like on Burrito.

### Steps To Reproduce

use latest (604) build Viaver and PS
Join with any version(1.9+) higher than server , I tested 1.12.2 and 1.18.1

### Server Version

This server is running NachoSpigot version git-NachoSpigot-"9c02430" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by crafter23456** [comment]
It's not intented to use 2 protocol hack plugins. Use Viaversion, Viabackwards and Viarewind but don't use via and PS!

**Comment by HowardZHY** [comment]
> It's not intented to use 2 protocol hack plugins. Use Viaversion, Viabackwards and Viarewind but don't use via and PS!

viabackwards is not for 1.8.8
and I still need support 1.6.X

**Comment by crafter23456** [comment]
You need only viaversion. Then you have all versions upwards. But only one protocolhack. Not 2. Not nachos fault.

**Comment by HowardZHY** [comment]
This is Nacho's bug. VV and PS works properly on Burrito. Nacho changed sth about netty so things might be abnormal.



At 2022-02-24 13:57:35, "crafter23456" ***@***.***> wrote:

You need only viaversion. Then you have all versions upwards. But only one protocolhack. Not 2. Not nachos fault.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Elierrr** [comment]
ProtocolSupport doesn't support 1.8 (the newer versions don't and only the older versions do which only support 1.7) and having ProtocolSupport + ViaVersion breaks ViaVersion as well. This also occurs on Burrito, not a Nacho issue. 

@Lucaskyy close

**Comment by HowardZHY** [comment]
> 

That does not occurs on Burrito. 
all players from 1.6,1.7,1.8 and latest mc played well on Burrito
[00:18:30] [Server thread/INFO]: [ClientStats] Version of players who joined:
[00:18:30] [Server thread/INFO]: - 1 players use version 1.7.6 - 1.7.10 (6%)
[00:18:30] [Server thread/INFO]: - 3 players use version 1.8 - 1.8.9 (17%)
[00:18:30] [Server thread/INFO]: - 1 players use version 15w39c/1.6.2 (6%)
[00:18:30] [Server thread/INFO]: - 1 players use version 15w41b/1.6.4 (6%)
[00:18:30] [Server thread/INFO]: - 1 players use version 1.10 - 1.10.2 (6%)
[00:18:30] [Server thread/INFO]: - 5 players use version 1.12.2 (28%)
[00:18:30] [Server thread/INFO]: - 3 players use version 1.16.4, 1.16.5 (17%)
[00:18:30] [Server thread/INFO]: - 3 players use version 1.18,1.18.1 (17%)

**Comment by HowardZHY** [comment]
https://user-images.githubusercontent.com/96782166/155924826-e5251f3d-eeb7-4c52-92dc-1c03f27a9ca2.mp4


https://user-images.githubusercontent.com/96782166/155924831-3629f90c-c2b4-4366-878d-bda44790d315.mp4
