### ISSUE TITLE
[ProtocolLib] INTERNAL ERROR: Unable to inject incoming channel

### ISSUE THREAD

**Issue by DrakMC** [CobbleSword/NachoSpigot#362]
### Observed Behavior

ProtocolLib not working with latest NachoSpigot. Error: https://pastebin.com/raw/wCm18sqk

### Expected Behavior

To make ProtocolLib work again.

### Steps To Reproduce

1. Start server
2. Error will show up in the console

### Server Version

git-NachoSpigot-"ec731d5" (MC: 1.8.8)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by HowardZHY** [comment]
use java 8

**Comment by CyberFlameGO** [comment]
> use java 8

iirc Java 15 works best on Nacho

**Comment by crafter23456** [comment]
He uses an old Protocollib. 4.7.0 and not the latest 4.8.0. that causes the issue. You know we removed the Protocollib patch because 4.8.0 fixed it internally. I didn't had the issue when I tested it on 4.8.0

**Comment by LewUwU** [comment]
> ### Observed Behavior
> ProtocolLib not working with latest NachoSpigot. Error: https://pastebin.com/raw/wCm18sqk
> 
> ### Expected Behavior
> To make ProtocolLib work again.
> 
> ### Steps To Reproduce
> 1. Start server
> 2. Error will show up in the console
> 
> ### Plugin List
> _No response_
> 
> ### Server Version
> git-NachoSpigot-"ec731d5" (MC: 1.8.8)
> 
> ### Other
> _No response_
> 
> ### Agreements
> * [x]  You were able to find this issue on the latest version of NachoSpigot.
> * [x]  You have confirmed that there aren’t any issues open regarding this bug.

Like @crafter23456 said, you're using a old protocollib version, you need to use 4.8.0+

**Comment by Elierrr** [comment]
> iirc Java 15 works best on Nacho

Java 17 works best and Java 15 is unsupported

> He uses an old Protocollib. 4.7.0 and not the latest 4.8.0. that causes the issue. You know we removed the Protocollib patch because 4.8.0 fixed it internally. I didn't had the issue when I tested it on 4.8.0

4.8.0 is still a snapshot which isn’t on the spigot page and thus not many people will use it. Also the ProtocolLib patch was removed in 4.7.0, not 4.8.0

**Comment by crafter23456** [comment]
> > iirc Java 15 works best on Nacho
> 
> Java 17 works best and Java 15 is unsupported by JDK providers and no longer getting updates
> 

I still use LTS Java 11 because of #327 

> > He uses an old Protocollib. 4.7.0 and not the latest 4.8.0. that causes the issue. You know we removed the Protocollib patch because 4.8.0 fixed it internally. I didn't had the issue when I tested it on 4.8.0
> 
> 4.8.0 is still a snapshot which isn’t on the spigot page and thus not many people will use it. Also the ProtocolLib patch was removed in 4.7.0, not 4.8.0

Yeah it's called snapshot but it uses literary everybody on 1.18.1+ and some ppl which know that the jenkins exist. So we bump netty if it released to spigot "officially" and literary nobody should use 4.7.0?
