### ISSUE TITLE
Gamerule String empty

### ISSUE THREAD

**Issue by crafter23456** [CobbleSword/NachoSpigot#366]
### Observed Behavior

![image](https://user-images.githubusercontent.com/64259198/156178105-0b09dff5-acb5-4317-92df-b9ac162aca53.png)

### Expected Behavior

write correct value and rule

### Steps To Reproduce

/gamerule (rule)

### Server Version

commit 86fb06bc045f81eb1b8d99cda371b18eafa07b87

### Other

https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-API/src/main/java/org/bukkit/command/defaults/GameRuleCommand.java#L42
https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/org/bukkit/craftbukkit/CraftWorld.java#L1393
(https://cdn.discordapp.com/attachments/732023562893787228/947265937525080114/unknown.png)
the string rule + value is somehow empty 🤔

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by Elierrr** [comment]
The gamerule command is handled by CommandGameRule in NMS, which uses "Game rule has been updated", not sure how you got that message. After testing, it works as expected and writes "Game rule has been updated".

**Comment by crafter23456** [comment]
I guess that's the Bukkit gameruke command. There should be Gamerule GAMERULE has been updated to FALSE/TRUE

**Comment by Elierrr** [comment]
> I guess that's the Bukkit gameruke command. There should be Gamerule GAMERULE has been updated to FALSE/TRUE

The Bukkit Minecraft commands are never even registered, not sure why they’re there. Also this issue should be closed.

**Comment by crafter23456** [comment]
![image](https://user-images.githubusercontent.com/64259198/162194587-e1c38ffe-b06b-425e-8f1c-412ae7cb4f7c.png)
First one with /gamerule... and second with /minecraft:gamerule...
https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-API/src/main/java/org/bukkit/command/defaults/GameRuleCommand.java#L42 from bukkit with value and its exactly the same text. 
https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/net/minecraft/server/CommandGamerule.java the normal minecraft directory doesnt show an output string. 
Doesnt bukkit change that?

**Comment by Elierrr** [comment]
NMS gamerule uses the lang file which is only “ Game rule has been updated”

**Comment by crafter23456** [comment]
But why it uses the bukkit string?

**Comment by Elierrr** [comment]
On the latest version it is using NMS string, on both client and console
![image_2022-04-07_165942](https://user-images.githubusercontent.com/71361901/162304431-c253e434-6a67-47b7-abf4-8f1d6d548b32.png)

**Comment by Elierrr** [comment]
The NMS sends the text at [line 50](https://github.com/CobbleSword/NachoSpigot/blob/74ed0ea729bdf19a4ba0329524b31669fdfea2a4/NachoSpigot-Server/src/main/java/net/minecraft/server/CommandGamerule.java#L50) using `commands.gamerule.success` from the lang file without putting any arguments and in the lang file `commands.gamerule.success` is "Game rule has been updated"

**Comment by crafter23456** [comment]
Sending the command in console ![image](https://user-images.githubusercontent.com/64259198/162393067-e09625b6-997a-4e70-ad0c-b6e7c2bd3b47.png)
Sending the command in chat
![image](https://user-images.githubusercontent.com/64259198/162393209-65aa31c0-596f-4410-9709-7a7ed44e6f1e.png)
![image](https://user-images.githubusercontent.com/64259198/162393232-0db37302-ca7f-4db5-9528-f4a7cb9b5f64.png)
So the problem is only client side with 1.18.2. I tested it with the vanilla 1.8.9 client and its doing the right thing.
> The Bukkit Minecraft commands are never even registered

so we can remove them?

**Comment by Elierrr** [comment]
> So the problem is only client side with 1.18.2. I tested it with the vanilla 1.8.9 client and its doing the right thing.

Probably because it has a different language file, we could put the proper arguments for it and 1.8 clients would ignore it

> so we can remove them?

We could, there’s no use for them.
