### ISSUE TITLE
Wildstacker not working with NachoSpigot

### ISSUE THREAD

**Issue by Redwolf223** [CobbleSword/NachoSpigot#378]
### Observed Behavior

Mob spawner won't spawn mobs when wildstacker is loaded.

Wildstacker version : 3.7.0

### Expected Behavior

For the spawner to work.

### Steps To Reproduce

Run NachoSpigot with Wildstacker 3.7.0

### Plugin List

Wildstacker

### Server Version

This server is running NachoSpigot version git-NachoSpigot-"0f4e14e" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by Elierrr** [comment]
Relevant Wildstacker issue: https://github.com/BG-Software-LLC/WildStacker/issues/484

**Comment by Elierrr** [comment]
The problem seems to be from NMS's World.isPlayerNearby() method

**Comment by Redwolf223** [comment]
I'm closing this as this has been resolved here: [https://github.com/BG-Software-LLC/WildStacker/issues/484](url)

thank you!
