### ISSUE TITLE
invalid keepalive 

### ISSUE THREAD

**Issue by ProtoGhost** [CobbleSword/NachoSpigot#379]
### Observed Behavior

Player lost connection: invalid keepalive
![Uploading image.png…]()

### Expected Behavior

you will understand I know 

### Steps To Reproduce

the latest version with this plugin ViaVersion, ProtocolLib, GodsEye

### Plugin List

ViaVersion, ProtocolLib, GodsEye(anticheat)

### Server Version

[15:36:47 INFO]: This server is running NachoSpigot version git-NachoSpigot-"0f4e14e" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
You are running the latest version

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by ProtoGhost** [comment]
![image](https://user-images.githubusercontent.com/67905221/159125468-6c61f014-5d27-41b4-b199-3e1e13acc9b7.png)

**Comment by HowardZHY** [comment]
is ur Liquidbounce 1.8.9 or 1.12.2?
I thonk Nacho "breaks" Viaver

**Comment by crafter23456** [comment]
> is ur Liquidbounce 1.8.9 or 1.12.2? I thonk Nacho "breaks" Viaver

no.

**Comment by crafter23456** [comment]
the server prevents his cheats from liquidbounce.

**Comment by HowardZHY** [comment]
so is that an anticheat problem?



At 2022-03-20 01:19:34, "crafter23456" ***@***.***> wrote:

the server prevents his cheats from liquidbounce.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HowardZHY** [comment]
anticheat prevents keepalive ?

**Comment by MWHunter** [comment]
You client is doing illegal protocol stuff and getting kicked for it.  Getting kicked for an invalid keepalive is standard minecraft 1.8 behavior as there's no way for a vanilla client to send the wrong keepalive.

**Comment by HowardZHY** [comment]
need more test to confirm its an client problem or plugin issue

**Comment by crafter23456** [comment]
no

**Comment by Elierrr** [comment]
Resolved in Discord @Lucaskyy

**Comment by Lucaskyy** [comment]
If you're testing an anti-cheat, use a different client :P 
Most things from LiquidBounce are detected (I think) since it's opensource.
And as you can see, LiquidBounce screws up the keepalive packet and thus you cannot even join the server. Good riddance.

**Comment by ProtoGhost** [comment]
https://media.discordapp.net/attachments/842679704736628746/954834144955875368/unknown.png

**Comment by ProtoGhost** [comment]
Same with lunar Client
