### ISSUE TITLE
generate-structures property ignored by nacho

### ISSUE THREAD

**Issue by Sneakometer** [CobbleSword/NachoSpigot#38]
NachoSpigot seems to ignore the `generate-structures` property when generating villages (possibly also other structures).
I have an empty void world and set `generate-structures=false` in `servers.properties`, but villages still generate in the air.
![2021-05-05_03 34 21](https://user-images.githubusercontent.com/50603525/117088817-dd341180-ad53-11eb-9e0a-d22223ec94ee.png)

I attached the world so it can be reproduced easily:
[world.zip](https://github.com/CobbleSword/NachoSpigot/files/6424690/world.zip)
Just flying around 1-2 minutes and you'll find some village.
Here are also coords if you don't have time: 9940 14 10795
_(This village isn't yet  explored in the world file above, so it will generate new)_

Java 8
Nacho latest build

**Comment by Lucaskyy** [comment]
I will take a look at this, thank you for letting us know!

**Comment by Sneakometer** [comment]
A workaround for now is to disable village generation in paper.yml's world-settings.
