### ISSUE TITLE
Sparky Anticheat having issues with NachoSpigot.

### ISSUE THREAD

**Issue by Mengyboi** [CobbleSword/NachoSpigot#382]
### Observed Behavior

https://cdn.discordapp.com/attachments/952219154092535818/955752276927066172/2022-03-22_15-50-06.mp4

### Expected Behavior

https://cdn.discordapp.com/attachments/952219154092535818/955752278751608852/2022-03-22_15-53-51.mp4

### Steps To Reproduce

Have Sparky in a server with nacho, start towering up and you'll see the issue.

### Plugin List

Tested with only Sparky.

### Server Version

![image](https://user-images.githubusercontent.com/85426783/159443586-314c10a0-e9c8-4318-829a-dc5080199313.png)
![image](https://user-images.githubusercontent.com/85426783/159443785-df87c814-5fb7-4470-8490-1246c6845de1.png)

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by sadcenter** [comment]
Do you use fast math and other features related to math?

**Comment by Mengyboi** [comment]
Found the issue, https://images-ext-2.discordapp.net/external/SuriGh8z66WaKd9L5gMUAC0v_YfGrLY50unAeOhJ-bI/https/ididntdoit.lol/4762476wbxia.png
