### ISSUE TITLE
Fireball explosions wrong knockback

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#39]
When you charge fireball in front of yourself and it explodes, it will knock you to the front, not from the explosion's location.

**Comment by Lucaskyy** [comment]
Does this only happen when using NachoSpigot or does it also happen in other forks like TacoSpigot?

**Comment by andreasdc** [comment]
@Lucaskyy I can't tell.

**Comment by LewUwU** [comment]
Try please

**Comment by Lucaskyy** [comment]
With this we can check if the issue is something done by us which makes it easier to find the issue.

**Comment by andreasdc** [comment]
@Lucaskyy well it can be problematic to test with another fork, but I can try with original explosion class.

**Comment by andreasdc** [comment]
@Lucaskyy I didn't check yet.

**Comment by Workinq** [comment]
> Any success yet? @andreasdc

The same behaviour occurs with regular TacoSpigot, I don't think this is an issue on your part.

**Comment by Lucaskyy** [comment]
Alright then, closing this issue for now. Might reopen it sometime.

**Comment by andreasdc** [comment]
@Lucaskyy it's the same with tnt.
