### ISSUE TITLE
Add packetevents (retrooper's) patch.

### ISSUE THREAD

**Issue by zhusun890** [CobbleSword/NachoSpigot#397]
### Describe the feature

Add packetevents (retrooper's) patch.

### Agreements

- [X] You have confirmed that this feature does not yet exist in the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this feature.

**Comment by 128931** [comment]
![63f](https://user-images.githubusercontent.com/101839340/161549901-1d7d7064-09a1-46a5-9f60-d3e29e7d93ab.jpg)
