### ISSUE TITLE
The "fast-operators" config option is broken again

### ISSUE THREAD

**Issue by windcolor-dev** [CobbleSword/NachoSpigot#407]
### Observed Behavior

Server operators don't load from "ops.json" after a server restart

### Expected Behavior

Server operators load properly

### Steps To Reproduce

- Enable "fast-operators" in nacho.yml
- Op a player
- Restart the server

### Plugin List

N/A

### Server Version

This server is running NachoSpigot version git-NachoSpigot-"74ed0ea" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
You are running the latest version

### Other

This issue was fixed in #157, but seems to have reappeared.

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.

**Comment by Elierrr** [comment]
See https://github.com/CobbleSword/NachoSpigot/issues/259#issuecomment-974642134
The comment is incorrect for this config, this is fixed in #406

**Comment by windcolor-dev** [comment]
Ah that was what i originally thought, [#150 (comment) ](https://github.com/CobbleSword/NachoSpigot/issues/150#issuecomment-903164214)
