### ISSUE TITLE
Releases API

### ISSUE THREAD

**Issue by matteoturini** [CobbleSword/NachoSpigot#48]
Make a releases API. I am making a docker container for nacho and it would be nice toa uto fetch latest version

**Comment by Lucaskyy** [comment]
Working on it.

**Comment by Lucaskyy** [comment]
Actually, you can also just download the latest jar every time the container starts, for example by running this command:
`wget https://nachodev.sculas.xyz/ -O nacho.zip && unzip nacho.zip && rm nacho.zip && mv NachoSpigot.jar server.jar`
Then just run `server.jar`
