### ISSUE TITLE
Better ViaVersion Patch

### ISSUE THREAD

**Issue by crafter23456** [CobbleSword/NachoSpigot#50]
Video example: https://drive.google.com/file/d/1ChiCEbdalCEL1ZK2Yvb_13lqdVWrUbKA/view?usp=sharing
![image](https://user-images.githubusercontent.com/64259198/120887905-d3712880-c5f5-11eb-9624-7f064ee0f2c1.png)
Viaversion discord said it could be made better 
idk but yeah it fixes if I stand at one place that I cant place blocks in me, but when I move I can still place blocks in me 😄 
With the paper in the name the bug is 100% there like without the via patch, when I rename it to a random name, when lucas patch gets triggered it works like in the video, not 100% good. 
& an option to disable the anticrash would be cool :P

**Comment by LewUwU** [comment]
The ViaVersion fix ins't NachoSpigot issue, Lucas only ported it for people that doesn't use Paper or Taco in the server brand.

And yes, i would like the option to enable/disable the anticrash system

**Comment by Lucaskyy** [comment]
I'm perfectly fine with removing the faulty patch from Paper as long as it doesn't cause issues.
And yes, I will add that.

**Comment by LewUwU** [comment]
> I'm perfectly fine with removing the faulty patch from Paper as long as it doesn't cause issues.
> And yes, I will add that.

If you remove the faulty patch of paper, then you're breaking tons of things now

**Comment by Lucaskyy** [comment]
Oh, that's lovely. Removing a broken patch that breaks other things.
I love programming.

**Comment by crafter23456** [comment]
With Paper in the brand the block-placement was completely buggy
With something other than Paper in the brand the block-placement is better but still like in the video
The viaversion discord said the patch could be made better that viaversion do it and not that patch. But I'm not a dev so I cant rate it. 
I could do some further testing cause they were a month old.
What you said to https://github.com/crafter23456/NachoSpigot2/commit/1e46d759353aa1888a391b2a6e9ffc2f23e3b549 not all but something like netty dependency updating 😄but like as above you can better estimate it.

**Comment by Lucaskyy** [comment]
Yeah, I need to update Netty, forgot to do that. Hope it doesn't cause issues hehe

**Comment by crafter23456** [comment]
Okay, I tested it, doesnt matter if I use Paper or a random name in the mod. But still same szenario like in the video.

**Comment by crafter23456** [comment]
So the anticrash option please & what with the viaversion thing? I mean I personally dont know what the viaversion discord mean with use via to patch it and dont make an own patch or like that.



> I'm perfectly fine with removing the faulty patch from Paper as long as it doesn't cause issues.
> And yes, I will add that.

**Comment by Lucaskyy** [comment]
Fixed in #72

**Comment by crafter23456** [comment]
Still the via problem
The class bukkit.listeners.protocol1_9to1_8.PaperPatch doesnt exists since the 14 april 2021 https://github.com/ViaVersion/ViaVersion/commit/61e47645958928e6243ff5a0ee2f81810d3e8f0b#diff-91357865906f00ef2b65e9fc58962908f0f45f7b9a61bb73077d771693f3ca34
Class<?> paperPatchClass = Class.forName(viaVersionPackage + "bukkit.listeners.protocol1_9to1_8.PaperPatch", true, cl);
What I think they changed is that the taco, paper and torch thing got removed that it get added to all versions below 1.9.
The weird thing is that when I rename it to "paper" its completely broken like before, when I call it Paper or like that its like in the video I sent in the first comment
