### ISSUE TITLE
NachoSpigot API maven

### ISSUE THREAD

**Issue by matteoturini** [CobbleSword/NachoSpigot#54]

**Comment by CyberFlameGO** [comment]
More info required @matteoturini. Please be descriptive in your issue so we can help you as best as possible! :)

**Comment by Lucaskyy** [comment]
I know what he means with this, this is not high priority as of know because Nacho hasn't added much into the API.

**Comment by HeathLoganCampbell** [comment]
Added to readme using jitpack
