### ISSUE TITLE
Java 16 Support

### ISSUE THREAD

**Issue by crafter23456** [CobbleSword/NachoSpigot#55]
Protocollib: https://pastebin.com/hiBmjbeG
Viaversion: https://pastebin.com/6hjDHq2Y
Via done in version 4 a bunch of api changes, but I prefer #50 
I dont saw any other things

**Comment by Sneakometer** [comment]
As a workaround, you could try using `--illegal-access` to fix the protocollib issue.

**Comment by Lucaskyy** [comment]
I'll try updating Javassist.

**Comment by crafter23456** [comment]
> I'll try updating Javassist.

should build fine with <version>3.28.0-GA</version> I tested it a few weeks ago https://github.com/crafter23456/NachoSpigot2/commit/1e46d759353aa1888a391b2a6e9ffc2f23e3b549

**Comment by crafter23456** [comment]
I tested it with latest so 3.28.0-GA but same error

**Comment by Lucaskyy** [comment]
Fixed now.
