### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by Lmmb74** [CobbleSword/NachoSpigot#6]
Hello. I'm trying to build the server but it fails throwing the following error:
`C:\Users\manci\Desktop\Github\NachoSpigot\NachoSpigot-API\src\main\java\org\spigotmc\CustomTimingsHandler.java:[26] The import jdk.internal.reflect.Reflection cannot be resolved`
`C:\Users\manci\Desktop\Github\NachoSpigot\NachoSpigot-API\src\main\java\org\spigotmc\CustomTimingsHandler.java:[54] Reflection cannot be resolved`

P.d.: Sorry if it's due to my ignorance and thanks for any help.

**Comment by MacacoLew** [comment]
Go to the main pom.xml and change the oss version to 9

**Comment by Lmmb74** [comment]
Still the same issue after doing that

**Comment by Lmmb74** [comment]
Well, using JDK 11 solved that issue, but now there's a new one:
`[ERROR] Failed to execute goal on project server: Could not resolve dependencies for project dev.cobblesword.nachospigot:server:jar:1.8.8-R0.2-SNAPSHOT: Could not find artifact org.spigotmc:minecraft-server:jar:1.8.8-SNAPSHOT in md_5-releases (http://repo.md-5.net/content/repositories/releases/)`

**Comment by Lmmb74** [comment]
Well, it seems that minecraft-server for 1.8.8 is not located at either md-5 repo or spigotmc repo, but https://maven.elmakers.com/repository/ does so I added it as repository and could finally get myself a fresh compilation. Thanks for your help :D. I'm closing this but you should add that repo to the main pom. Take care and happy new year :D
