### ISSUE TITLE
Could not call method 'public static org.bukkit.inventory.meta.ItemMeta

### ISSUE THREAD

**Issue by AltarRiza** [CobbleSword/NachoSpigot#64]
Hello i use strikepractice with default setting. https://pastebin.ubuntu.com/p/zCC8G3TC5j/ . With paper or spigot does not give this error

**Comment by Lucaskyy** [comment]
Looks like an easy fix to me, I will do that when I'm home.

**Comment by AltarRiza** [comment]
I am waiting

**Comment by AltarRiza** [comment]
I'm still waiting

**Comment by CyberFlameGO** [comment]
Please be a little more patient, but here. @Lucaskyy Boop!
