### ISSUE TITLE
Can't change kb settings

### ISSUE THREAD

**Issue by zNoah-1** [CobbleSword/NachoSpigot#68]
Doesn't matter if I change it through /kb set or directly into knockback.json, it does not change at all. Tried restarting but nothing.

Even tried 100 vertical and does not change a thing.

**Comment by windcolor-dev** [comment]
Took a look at the knockback commit, and it doesn't actually seem to change the knockback mechanics/amounts.

**Comment by Outfluencer** [comment]
yeah its not implimented

**Comment by Lucaskyy** [comment]
I ported the knockback over from CobbleSword/KnockbackSpigot

This needs fixing yeah.

**Comment by windcolor-dev** [comment]
I think that the actual kb calculating and sending is in EntityHuman.java in the attack method

**Comment by Rastrian** [comment]
I will take a look into this soon, and also implement async kb, hit detection and potion.

**Comment by Lucaskyy** [comment]
> I will take a look into this soon, and also implement async kb, hit detection and potion.

That would be awesome :)

**Comment by Lucaskyy** [comment]
This is temporary fixed until the new system is in place :)

**Comment by Rastrian** [comment]
Close this issue @Lucaskyy 
https://github.com/CobbleSword/NachoSpigot/pull/242/files

**Comment by Rastrian** [comment]
Close this issue @Lucaskyy
https://github.com/CobbleSword/NachoSpigot/pull/242
