### ISSUE TITLE
Item duplication with hoppers

### ISSUE THREAD

**Issue by AhmHkn0** [CobbleSword/NachoSpigot#75]
I tried on TacoSpigot and didn't duplicated.
It is only on NachoSpigot.

https://www.youtube.com/watch?v=mehYU2g53uw

**Comment by CyberFlameGO** [comment]
Oh? @Lucaskyy @LewUwU @HeathLoganCampbell this is an interesting one

**Comment by Lucaskyy** [comment]
Uhhhh, hahaha. That's definitely not right.

Can you try adding IllegalStack (plugin) to your server and check if that fixes it? Just curious.

**Comment by AhmHkn0** [comment]
IllegalStack doesn't fix it. I already tried.

**Comment by benfiratkaya** [comment]
I try this bug. It's working with zero plugin.

**Comment by Lucaskyy** [comment]
^^
