### ISSUE TITLE
Server crash when map "world" start loading

### ISSUE THREAD

**Issue by AzonFR** [CobbleSword/NachoSpigot#8]
Hey, i was using mSpigot and i've seen your fork so i decided to test it but when the server starts to load the default world, it just crash
Server logs: https://pastebin.com/8WAg4itQ
Crash report: https://pastebin.com/3vQ6kTJw

**Comment by MacacoLew** [comment]
what java version are u using

**Comment by sadcenter** [comment]
I think its because of your java version

**Comment by Oberfail** [comment]
Even with a fresh install of NachSpigot, it crashes upon world load.

**Comment by PaulBGD** [comment]
You need a version of NachoSpigot compiled for Java 8 if you're going to use Java 8.

Java 8's ByteBuffer doesn't change the signature of `clear`, so it defers to super which returns a `Buffer`: https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html
Java 9's ByteBuffer changes the signature to return another `ByteBuffer`, which makes any use of `ByteBuffer.clear` compiled in Java 9 unusable on JRE8: https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#clear--

**Comment by CyberFlameGO** [comment]
@AzonFR

**Comment by CyberFlameGO** [comment]
@HeathLoganCampbell I think this seems good to close

**Comment by Lucaskyy** [comment]
Fixed in current commit/release.

**Closing.**
