### ISSUE TITLE
Possible Minecraft License violation

### ISSUE THREAD

**Issue by matteoturini** [CobbleSword/NachoSpigot#83]
Minecraft's License prohibits code redistribution, yet it is available on this repository.

**Comment by Geolykt** [comment]
This is the same for mostly all pre-1.9 bukkit forks, what else did you expect?

**Comment by CyberFlameGO** [comment]
Hey there, @matteoturini! We're aware of this, however we're not going to take action until we're served with a DMCA Takedown notice. Thanks for your concerns, take care!

**Comment by Lucaskyy** [comment]
We are aware and there's no going back now. If Mojang decides to DMCA this repo, then that means the end of this project. That's just how it is.
