### ISSUE TITLE
Protocollib patch broken

### ISSUE THREAD

**Issue by crafter23456** [CobbleSword/NachoSpigot#84]
https://paste.gg/p/anonymous/e7345e9f980a44caa39fb975fc887977
Since I switched from build #521 to build #522
![image](https://user-images.githubusercontent.com/64259198/123375445-12592500-d589-11eb-91f2-63e2ed5b0c3b.png)

**Comment by NightMite** [comment]
If you are running Java 16, patching Protocollib will not work. Use Java 15 instead.

**Comment by crafter23456** [comment]
Its Java 11 (you can see it in the error log :P)

**Comment by NightMite** [comment]
Ok, but im using the latest build on java 11 and it's completly fine.

**Comment by CyberFlameGO** [comment]
Relevant file to this issue: https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/dev/cobblesword/nachospigot/patches/RuntimePatches.java

**Comment by refractored** [comment]
The latest dev builds are for 1.17
You can download a build for 1.8-1.16 here : https://www.spigotmc.org/resources/protocollib.1997/download?version=383725

**Comment by crafter23456** [comment]
> The latest dev builds are for 1.17, Which is the build you are using currently.
> You can download a build for 1.8-1.16 here, This should work just fine. : https://www.spigotmc.org/resources/protocollib.1997/download?version=383725
He adds 1.8-1.16 support. But why should it work on an older 1.17 build and not on the latest 1.17 build :D

**Comment by refractored** [comment]
I dont know, Its a **dev** build for **1.17** so it makes sense all of a sudden the newest builds dont work. Its not like your losing functionality anyways by using a 1.8-1.16 build.

**Comment by NightMite** [comment]
I tried patching the latest ProtocolLib dev build on Java 11 and it worked fine.

**Comment by crafter23456** [comment]
> I tried patching the latest ProtocolLib dev build on Java 11 and it worked fine.

You are on ProtocolLib v4.7.0-SNAPSHOT-b522 and latest Nachospigot from https://nachodev.sculas.xyz/ ?

**Comment by Lucaskyy** [comment]
The issue relies in Java 16, not ProtocolLib. Like NightMite said, use Java 15 or lower.

**Comment by crafter23456** [comment]
watch line 56 
https://paste.gg/p/anonymous/e7345e9f980a44caa39fb975fc887977
its java 11
