### ISSUE TITLE
ProtocolLib Issues

### ISSUE THREAD

**Issue by KolakZ** [CobbleSword/NachoSpigot#86]
I got this error on server startup when using `NachoSpigot`:
https://bin.bloom.host/jorubireli.properties

**Comment by KolakZ** [comment]
Follow up: I was not able to reproduce this issue on `Paper`.

**Comment by Lucaskyy** [comment]
Use Java 15 or lower and use the 1.8-1.16 build of ProtocolLib.

**Comment by Lucaskyy** [comment]
@KolakZ Please use the latest version of ProtocolLib with any Java version you want to use. Java 16 is recommended.
