### ISSUE TITLE
HideAndCustomPlugins Issues

### ISSUE THREAD

**Issue by KolakZ** [CobbleSword/NachoSpigot#88]
I got this error on server startup when using `NachoSpigot`:
https://bin.bloom.host/rihudipuyu.properties

**Comment by KolakZ** [comment]
Follow up: I was not able to reproduce this issue on `Paper`.

**Comment by CyberFlameGO** [comment]
What version of Java are you using?

**Comment by KolakZ** [comment]
Java 8.

**Comment by CyberFlameGO** [comment]
Try Java 15 and let me know your results please!

**Comment by KolakZ** [comment]
My plugins don't work with Java 15.

**Comment by CyberFlameGO** [comment]
Like what? Why don't they work?

**Comment by CyberFlameGO** [comment]
#89 should now just be communicated here

**Comment by refractored** [comment]
Make sure you use Protocollib 4.6.0 and java 8-15

**Comment by Lucaskyy** [comment]
@KolakZ This is NOT a NachoSpigot issue. Please look at the error, this is a ProtocolLib issue.
