### ISSUE TITLE
ChatItem Issues

### ISSUE THREAD

**Issue by KolakZ** [CobbleSword/NachoSpigot#89]
I got this error on server startup when using `NachoSpigot`:
https://bin.bloom.host/asojagizuk.css

**Comment by KolakZ** [comment]
Follow up: I was not able to reproduce this issue on `Paper`.

**Comment by CyberFlameGO** [comment]
What version of Java are you using?

**Comment by KolakZ** [comment]
Java 8.

**Comment by CyberFlameGO** [comment]
Could you try using Java 15 please?

**Comment by KolakZ** [comment]
My plugins don't work with Java 15.

**Comment by CyberFlameGO** [comment]
Like what, and why don't they work?
