### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yoczus** [CobbleSword/NachoSpigot#96]
[ERROR] Plugin com.lukegb.mojo:gitdescribe-maven-plugin:1.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.lukegb.mojo:gitdescribe-maven-plugin:jar:1.3: 1 problem was encountered while building the effective model
[ERROR] [FATAL] Non-parseable POM C:\Users\yoczu\.m2\repository\com\lukegb\mojo\gitdescribe-maven-plugin\1.3\gitdescribe-maven-plugin-1.3.pom: end tag name </head> must be the same as start tag <link> from line 7 (position: TEXT seen ...</style>\n  </head>... @31:10)  @ line 31, column 10
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by yoczus** [comment]
bump

**Comment by CyberFlameGO** [comment]
Read the error please. It looks like something is up with Maven on your end

**Comment by yoczus** [comment]
I deleted the repositories from the maven cache and it worked, thanks.
