### ISSUE TITLE
Ghost spawners

### ISSUE THREAD

**Issue by dule0004** [CobbleSword/NachoSpigot#97]
When player break spawner and leave chunk for 5 seconds. After 5 seconds player go back to location of spawner. Mobs will spawns but there is no spawner on this location.

**Comment by TheGeyik** [comment]
Duplicate #49 Same issue

**Comment by CyberFlameGO** [comment]
Plugins list?

**Comment by dule0004** [comment]
This is a list of plugins:  PlayerPoints, SpigotPreventTab, BookDuplicationFix, SCPotionControl, NoSleepCMDs, SkinsRestorer, antiRedstoneClock, MobFarmManager, Elixirs, ViaVersion, CropHopper, ItemRestrict, Relative_Coordculator, CoreProtect, LuckPerms, WorldEdit, OreAnnouncer, OpenInv, SignCooldown, ClearLag, EndPortalFix, Yamler, ProtocolLib, MVdWPlaceholderAPI, ExecuteEverywhere, IPWhitelist, FactionsFix, FeatherBoard, AntiDisconnectSpam, Vault, HolographicDisplays, WorldGuard, ChestCommands, EditableSign, TradePlus, ChestCommandsLogger, PlayerVaults, AreaShop, Essentials, HeadDatabase, TradePlusVanish, Citizens, EssentialsChat, CrazyAuctions, ChestShop, ArmorStandTools, EssentialsSpawn, NickRemover, CrateReloaded, SellStick, ObsidianDestroyer, Factions, FactionsFly, FactionsCauldron, FactionsTop, FTopHolograms, PvPManager, BungeeTabListPlus, GenBucket, FBasics, WitherSranje, ChatControl, IllegalStack, KoTH, SilkSpawners, FactionsSilkDB, FactionsAdventure, PvPManagerTradePlus, SCSurvivalPlugin.

  But there is no problem with plugins. We tried without plugins on clean world and bug agains happens

**Comment by baticag** [comment]
Okay no. Plugins aren't problem. We tested the problem with clean plugins folder and with new world. Only NachoSpigot. Also we tried with same clean installation but with PaperSpigot and problem is gone. There is some Thread.dump patch that PaperSpigot imeplemented and you haven't here, so please look into this and fix it, because that has nothing to do with our installation.

**Comment by Lucaskyy** [comment]
This project has been abandoned for some time now, use something else. IonSpigot looks fine.

**Comment by HeathLoganCampbell** [comment]
Mmmmh? We haven't made anything special to mob spawners by the looks of it, I'll have to look into Tile Entities to see if anything there could be causing the issue because if that's the case other things would be broken too

**Comment by BeyazPolisli** [comment]
fixed problem but required test 

https://nachodev.sculas.xyz/

**Comment by Lucaskyy** [comment]
@TheGeyik It should be fixed in the latest version! Could you please try again? :) Reopen this issue if it still occurs.
